// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoiceapplication type in the database.
	Label = "invoice_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldBuyerType holds the string denoting the buyer_type field in the database.
	FieldBuyerType = "buyer_type"
	// FieldBuyerName holds the string denoting the buyer_name field in the database.
	FieldBuyerName = "buyer_name"
	// FieldBuyerTaxNo holds the string denoting the buyer_tax_no field in the database.
	FieldBuyerTaxNo = "buyer_tax_no"
	// FieldBuyerEmail holds the string denoting the buyer_email field in the database.
	FieldBuyerEmail = "buyer_email"
	// FieldBuyerPhone holds the string denoting the buyer_phone field in the database.
	FieldBuyerPhone = "buyer_phone"
	// FieldBuyerAddress holds the string denoting the buyer_address field in the database.
	FieldBuyerAddress = "buyer_address"
	// FieldBuyerBankName holds the string denoting the buyer_bank_name field in the database.
	FieldBuyerBankName = "buyer_bank_name"
	// FieldBuyerBankAccount holds the string denoting the buyer_bank_account field in the database.
	FieldBuyerBankAccount = "buyer_bank_account"
	// FieldInvoiceAmount holds the string denoting the invoice_amount field in the database.
	FieldInvoiceAmount = "invoice_amount"
	// FieldInvoiceType holds the string denoting the invoice_type field in the database.
	FieldInvoiceType = "invoice_type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldTaxRate holds the string denoting the tax_rate field in the database.
	FieldTaxRate = "tax_rate"
	// FieldTaxClassificationCode holds the string denoting the tax_classification_code field in the database.
	FieldTaxClassificationCode = "tax_classification_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderOrderID holds the string denoting the provider_order_id field in the database.
	FieldProviderOrderID = "provider_order_id"
	// FieldProviderOrderNo holds the string denoting the provider_order_no field in the database.
	FieldProviderOrderNo = "provider_order_no"
	// FieldInvoiceCode holds the string denoting the invoice_code field in the database.
	FieldInvoiceCode = "invoice_code"
	// FieldInvoiceNo holds the string denoting the invoice_no field in the database.
	FieldInvoiceNo = "invoice_no"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldRequestPayloadSnapshot holds the string denoting the request_payload_snapshot field in the database.
	FieldRequestPayloadSnapshot = "request_payload_snapshot"
	// FieldResponsePayloadSnapshot holds the string denoting the response_payload_snapshot field in the database.
	FieldResponsePayloadSnapshot = "response_payload_snapshot"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldPdfFileData holds the string denoting the pdf_file_data field in the database.
	FieldPdfFileData = "pdf_file_data"
	// FieldOfdFileData holds the string denoting the ofd_file_data field in the database.
	FieldOfdFileData = "ofd_file_data"
	// FieldXMLFileData holds the string denoting the xml_file_data field in the database.
	FieldXMLFileData = "xml_file_data"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the invoiceapplication in the database.
	Table = "invoice_applications"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_applications"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "invoice_application_orders"
	// OrdersInverseTable is the table name for the InvoiceApplicationOrder entity.
	// It exists in this package in order to avoid circular dependency with the "invoiceapplicationorder" package.
	OrdersInverseTable = "invoice_application_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "invoice_application_id"
)

// Columns holds all SQL columns for invoiceapplication fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserEmail,
	FieldBuyerType,
	FieldBuyerName,
	FieldBuyerTaxNo,
	FieldBuyerEmail,
	FieldBuyerPhone,
	FieldBuyerAddress,
	FieldBuyerBankName,
	FieldBuyerBankAccount,
	FieldInvoiceAmount,
	FieldInvoiceType,
	FieldContent,
	FieldTaxRate,
	FieldTaxClassificationCode,
	FieldStatus,
	FieldProvider,
	FieldProviderOrderID,
	FieldProviderOrderNo,
	FieldInvoiceCode,
	FieldInvoiceNo,
	FieldIssuedAt,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldRequestPayloadSnapshot,
	FieldResponsePayloadSnapshot,
	FieldRetryCount,
	FieldPdfFileData,
	FieldOfdFileData,
	FieldXMLFileData,
	FieldSubmittedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserEmail holds the default value on creation for the "user_email" field.
	DefaultUserEmail string
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultBuyerType holds the default value on creation for the "buyer_type" field.
	DefaultBuyerType string
	// BuyerTypeValidator is a validator for the "buyer_type" field. It is called by the builders before save.
	BuyerTypeValidator func(string) error
	// BuyerNameValidator is a validator for the "buyer_name" field. It is called by the builders before save.
	BuyerNameValidator func(string) error
	// DefaultBuyerTaxNo holds the default value on creation for the "buyer_tax_no" field.
	DefaultBuyerTaxNo string
	// BuyerTaxNoValidator is a validator for the "buyer_tax_no" field. It is called by the builders before save.
	BuyerTaxNoValidator func(string) error
	// DefaultBuyerEmail holds the default value on creation for the "buyer_email" field.
	DefaultBuyerEmail string
	// BuyerEmailValidator is a validator for the "buyer_email" field. It is called by the builders before save.
	BuyerEmailValidator func(string) error
	// DefaultBuyerPhone holds the default value on creation for the "buyer_phone" field.
	DefaultBuyerPhone string
	// BuyerPhoneValidator is a validator for the "buyer_phone" field. It is called by the builders before save.
	BuyerPhoneValidator func(string) error
	// DefaultBuyerAddress holds the default value on creation for the "buyer_address" field.
	DefaultBuyerAddress string
	// DefaultBuyerBankName holds the default value on creation for the "buyer_bank_name" field.
	DefaultBuyerBankName string
	// BuyerBankNameValidator is a validator for the "buyer_bank_name" field. It is called by the builders before save.
	BuyerBankNameValidator func(string) error
	// DefaultBuyerBankAccount holds the default value on creation for the "buyer_bank_account" field.
	DefaultBuyerBankAccount string
	// BuyerBankAccountValidator is a validator for the "buyer_bank_account" field. It is called by the builders before save.
	BuyerBankAccountValidator func(string) error
	// DefaultInvoiceType holds the default value on creation for the "invoice_type" field.
	DefaultInvoiceType string
	// InvoiceTypeValidator is a validator for the "invoice_type" field. It is called by the builders before save.
	InvoiceTypeValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultTaxRate holds the default value on creation for the "tax_rate" field.
	DefaultTaxRate string
	// TaxRateValidator is a validator for the "tax_rate" field. It is called by the builders before save.
	TaxRateValidator func(string) error
	// DefaultTaxClassificationCode holds the default value on creation for the "tax_classification_code" field.
	DefaultTaxClassificationCode string
	// TaxClassificationCodeValidator is a validator for the "tax_classification_code" field. It is called by the builders before save.
	TaxClassificationCodeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultProviderOrderID holds the default value on creation for the "provider_order_id" field.
	DefaultProviderOrderID string
	// ProviderOrderIDValidator is a validator for the "provider_order_id" field. It is called by the builders before save.
	ProviderOrderIDValidator func(string) error
	// DefaultProviderOrderNo holds the default value on creation for the "provider_order_no" field.
	DefaultProviderOrderNo string
	// ProviderOrderNoValidator is a validator for the "provider_order_no" field. It is called by the builders before save.
	ProviderOrderNoValidator func(string) error
	// DefaultInvoiceCode holds the default value on creation for the "invoice_code" field.
	DefaultInvoiceCode string
	// InvoiceCodeValidator is a validator for the "invoice_code" field. It is called by the builders before save.
	InvoiceCodeValidator func(string) error
	// DefaultInvoiceNo holds the default value on creation for the "invoice_no" field.
	DefaultInvoiceNo string
	// InvoiceNoValidator is a validator for the "invoice_no" field. It is called by the builders before save.
	InvoiceNoValidator func(string) error
	// DefaultLastErrorCode holds the default value on creation for the "last_error_code" field.
	DefaultLastErrorCode string
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultLastErrorMessage holds the default value on creation for the "last_error_message" field.
	DefaultLastErrorMessage string
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultPdfFileData holds the default value on creation for the "pdf_file_data" field.
	DefaultPdfFileData string
	// DefaultOfdFileData holds the default value on creation for the "ofd_file_data" field.
	DefaultOfdFileData string
	// DefaultXMLFileData holds the default value on creation for the "xml_file_data" field.
	DefaultXMLFileData string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByBuyerType orders the results by the buyer_type field.
func ByBuyerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerType, opts...).ToFunc()
}

// ByBuyerName orders the results by the buyer_name field.
func ByBuyerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerName, opts...).ToFunc()
}

// ByBuyerTaxNo orders the results by the buyer_tax_no field.
func ByBuyerTaxNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerTaxNo, opts...).ToFunc()
}

// ByBuyerEmail orders the results by the buyer_email field.
func ByBuyerEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerEmail, opts...).ToFunc()
}

// ByBuyerPhone orders the results by the buyer_phone field.
func ByBuyerPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerPhone, opts...).ToFunc()
}

// ByBuyerAddress orders the results by the buyer_address field.
func ByBuyerAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerAddress, opts...).ToFunc()
}

// ByBuyerBankName orders the results by the buyer_bank_name field.
func ByBuyerBankName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerBankName, opts...).ToFunc()
}

// ByBuyerBankAccount orders the results by the buyer_bank_account field.
func ByBuyerBankAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerBankAccount, opts...).ToFunc()
}

// ByInvoiceAmount orders the results by the invoice_amount field.
func ByInvoiceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceAmount, opts...).ToFunc()
}

// ByInvoiceType orders the results by the invoice_type field.
func ByInvoiceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceType, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByTaxRate orders the results by the tax_rate field.
func ByTaxRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxRate, opts...).ToFunc()
}

// ByTaxClassificationCode orders the results by the tax_classification_code field.
func ByTaxClassificationCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxClassificationCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderOrderID orders the results by the provider_order_id field.
func ByProviderOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderOrderID, opts...).ToFunc()
}

// ByProviderOrderNo orders the results by the provider_order_no field.
func ByProviderOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderOrderNo, opts...).ToFunc()
}

// ByInvoiceCode orders the results by the invoice_code field.
func ByInvoiceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceCode, opts...).ToFunc()
}

// ByInvoiceNo orders the results by the invoice_no field.
func ByInvoiceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNo, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByPdfFileData orders the results by the pdf_file_data field.
func ByPdfFileData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfFileData, opts...).ToFunc()
}

// ByOfdFileData orders the results by the ofd_file_data field.
func ByOfdFileData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfdFileData, opts...).ToFunc()
}

// ByXMLFileData orders the results by the xml_file_data field.
func ByXMLFileData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXMLFileData, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
