// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserEmail, v))
}

// BuyerType applies equality check predicate on the "buyer_type" field. It's identical to BuyerTypeEQ.
func BuyerType(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerType, v))
}

// BuyerName applies equality check predicate on the "buyer_name" field. It's identical to BuyerNameEQ.
func BuyerName(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerTaxNo applies equality check predicate on the "buyer_tax_no" field. It's identical to BuyerTaxNoEQ.
func BuyerTaxNo(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerTaxNo, v))
}

// BuyerEmail applies equality check predicate on the "buyer_email" field. It's identical to BuyerEmailEQ.
func BuyerEmail(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerEmail, v))
}

// BuyerPhone applies equality check predicate on the "buyer_phone" field. It's identical to BuyerPhoneEQ.
func BuyerPhone(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerPhone, v))
}

// BuyerAddress applies equality check predicate on the "buyer_address" field. It's identical to BuyerAddressEQ.
func BuyerAddress(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerBankName applies equality check predicate on the "buyer_bank_name" field. It's identical to BuyerBankNameEQ.
func BuyerBankName(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerBankName, v))
}

// BuyerBankAccount applies equality check predicate on the "buyer_bank_account" field. It's identical to BuyerBankAccountEQ.
func BuyerBankAccount(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerBankAccount, v))
}

// InvoiceAmount applies equality check predicate on the "invoice_amount" field. It's identical to InvoiceAmountEQ.
func InvoiceAmount(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceAmount, v))
}

// InvoiceType applies equality check predicate on the "invoice_type" field. It's identical to InvoiceTypeEQ.
func InvoiceType(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldContent, v))
}

// TaxRate applies equality check predicate on the "tax_rate" field. It's identical to TaxRateEQ.
func TaxRate(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxRate, v))
}

// TaxClassificationCode applies equality check predicate on the "tax_classification_code" field. It's identical to TaxClassificationCodeEQ.
func TaxClassificationCode(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxClassificationCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProvider, v))
}

// ProviderOrderID applies equality check predicate on the "provider_order_id" field. It's identical to ProviderOrderIDEQ.
func ProviderOrderID(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProviderOrderID, v))
}

// ProviderOrderNo applies equality check predicate on the "provider_order_no" field. It's identical to ProviderOrderNoEQ.
func ProviderOrderNo(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProviderOrderNo, v))
}

// InvoiceCode applies equality check predicate on the "invoice_code" field. It's identical to InvoiceCodeEQ.
func InvoiceCode(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceCode, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceNo, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldIssuedAt, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldLastErrorMessage, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRetryCount, v))
}

// PdfFileData applies equality check predicate on the "pdf_file_data" field. It's identical to PdfFileDataEQ.
func PdfFileData(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldPdfFileData, v))
}

// OfdFileData applies equality check predicate on the "ofd_file_data" field. It's identical to OfdFileDataEQ.
func OfdFileData(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldOfdFileData, v))
}

// XMLFileData applies equality check predicate on the "xml_file_data" field. It's identical to XMLFileDataEQ.
func XMLFileData(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldXMLFileData, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldSubmittedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUserID, vs...))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldUserEmail, v))
}

// BuyerTypeEQ applies the EQ predicate on the "buyer_type" field.
func BuyerTypeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerType, v))
}

// BuyerTypeNEQ applies the NEQ predicate on the "buyer_type" field.
func BuyerTypeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerType, v))
}

// BuyerTypeIn applies the In predicate on the "buyer_type" field.
func BuyerTypeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerType, vs...))
}

// BuyerTypeNotIn applies the NotIn predicate on the "buyer_type" field.
func BuyerTypeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerType, vs...))
}

// BuyerTypeGT applies the GT predicate on the "buyer_type" field.
func BuyerTypeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerType, v))
}

// BuyerTypeGTE applies the GTE predicate on the "buyer_type" field.
func BuyerTypeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerType, v))
}

// BuyerTypeLT applies the LT predicate on the "buyer_type" field.
func BuyerTypeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerType, v))
}

// BuyerTypeLTE applies the LTE predicate on the "buyer_type" field.
func BuyerTypeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerType, v))
}

// BuyerTypeContains applies the Contains predicate on the "buyer_type" field.
func BuyerTypeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerType, v))
}

// BuyerTypeHasPrefix applies the HasPrefix predicate on the "buyer_type" field.
func BuyerTypeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerType, v))
}

// BuyerTypeHasSuffix applies the HasSuffix predicate on the "buyer_type" field.
func BuyerTypeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerType, v))
}

// BuyerTypeEqualFold applies the EqualFold predicate on the "buyer_type" field.
func BuyerTypeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerType, v))
}

// BuyerTypeContainsFold applies the ContainsFold predicate on the "buyer_type" field.
func BuyerTypeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerType, v))
}

// BuyerNameEQ applies the EQ predicate on the "buyer_name" field.
func BuyerNameEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerName, v))
}

// BuyerNameNEQ applies the NEQ predicate on the "buyer_name" field.
func BuyerNameNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerName, v))
}

// BuyerNameIn applies the In predicate on the "buyer_name" field.
func BuyerNameIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerName, vs...))
}

// BuyerNameNotIn applies the NotIn predicate on the "buyer_name" field.
func BuyerNameNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerName, vs...))
}

// BuyerNameGT applies the GT predicate on the "buyer_name" field.
func BuyerNameGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerName, v))
}

// BuyerNameGTE applies the GTE predicate on the "buyer_name" field.
func BuyerNameGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerName, v))
}

// BuyerNameLT applies the LT predicate on the "buyer_name" field.
func BuyerNameLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerName, v))
}

// BuyerNameLTE applies the LTE predicate on the "buyer_name" field.
func BuyerNameLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerName, v))
}

// BuyerNameContains applies the Contains predicate on the "buyer_name" field.
func BuyerNameContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerName, v))
}

// BuyerNameHasPrefix applies the HasPrefix predicate on the "buyer_name" field.
func BuyerNameHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerName, v))
}

// BuyerNameHasSuffix applies the HasSuffix predicate on the "buyer_name" field.
func BuyerNameHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerName, v))
}

// BuyerNameEqualFold applies the EqualFold predicate on the "buyer_name" field.
func BuyerNameEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerName, v))
}

// BuyerNameContainsFold applies the ContainsFold predicate on the "buyer_name" field.
func BuyerNameContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerName, v))
}

// BuyerTaxNoEQ applies the EQ predicate on the "buyer_tax_no" field.
func BuyerTaxNoEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerTaxNo, v))
}

// BuyerTaxNoNEQ applies the NEQ predicate on the "buyer_tax_no" field.
func BuyerTaxNoNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerTaxNo, v))
}

// BuyerTaxNoIn applies the In predicate on the "buyer_tax_no" field.
func BuyerTaxNoIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerTaxNo, vs...))
}

// BuyerTaxNoNotIn applies the NotIn predicate on the "buyer_tax_no" field.
func BuyerTaxNoNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerTaxNo, vs...))
}

// BuyerTaxNoGT applies the GT predicate on the "buyer_tax_no" field.
func BuyerTaxNoGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerTaxNo, v))
}

// BuyerTaxNoGTE applies the GTE predicate on the "buyer_tax_no" field.
func BuyerTaxNoGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerTaxNo, v))
}

// BuyerTaxNoLT applies the LT predicate on the "buyer_tax_no" field.
func BuyerTaxNoLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerTaxNo, v))
}

// BuyerTaxNoLTE applies the LTE predicate on the "buyer_tax_no" field.
func BuyerTaxNoLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerTaxNo, v))
}

// BuyerTaxNoContains applies the Contains predicate on the "buyer_tax_no" field.
func BuyerTaxNoContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerTaxNo, v))
}

// BuyerTaxNoHasPrefix applies the HasPrefix predicate on the "buyer_tax_no" field.
func BuyerTaxNoHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerTaxNo, v))
}

// BuyerTaxNoHasSuffix applies the HasSuffix predicate on the "buyer_tax_no" field.
func BuyerTaxNoHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerTaxNo, v))
}

// BuyerTaxNoEqualFold applies the EqualFold predicate on the "buyer_tax_no" field.
func BuyerTaxNoEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerTaxNo, v))
}

// BuyerTaxNoContainsFold applies the ContainsFold predicate on the "buyer_tax_no" field.
func BuyerTaxNoContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerTaxNo, v))
}

// BuyerEmailEQ applies the EQ predicate on the "buyer_email" field.
func BuyerEmailEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerEmail, v))
}

// BuyerEmailNEQ applies the NEQ predicate on the "buyer_email" field.
func BuyerEmailNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerEmail, v))
}

// BuyerEmailIn applies the In predicate on the "buyer_email" field.
func BuyerEmailIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerEmail, vs...))
}

// BuyerEmailNotIn applies the NotIn predicate on the "buyer_email" field.
func BuyerEmailNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerEmail, vs...))
}

// BuyerEmailGT applies the GT predicate on the "buyer_email" field.
func BuyerEmailGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerEmail, v))
}

// BuyerEmailGTE applies the GTE predicate on the "buyer_email" field.
func BuyerEmailGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerEmail, v))
}

// BuyerEmailLT applies the LT predicate on the "buyer_email" field.
func BuyerEmailLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerEmail, v))
}

// BuyerEmailLTE applies the LTE predicate on the "buyer_email" field.
func BuyerEmailLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerEmail, v))
}

// BuyerEmailContains applies the Contains predicate on the "buyer_email" field.
func BuyerEmailContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerEmail, v))
}

// BuyerEmailHasPrefix applies the HasPrefix predicate on the "buyer_email" field.
func BuyerEmailHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerEmail, v))
}

// BuyerEmailHasSuffix applies the HasSuffix predicate on the "buyer_email" field.
func BuyerEmailHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerEmail, v))
}

// BuyerEmailEqualFold applies the EqualFold predicate on the "buyer_email" field.
func BuyerEmailEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerEmail, v))
}

// BuyerEmailContainsFold applies the ContainsFold predicate on the "buyer_email" field.
func BuyerEmailContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerEmail, v))
}

// BuyerPhoneEQ applies the EQ predicate on the "buyer_phone" field.
func BuyerPhoneEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerPhone, v))
}

// BuyerPhoneNEQ applies the NEQ predicate on the "buyer_phone" field.
func BuyerPhoneNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerPhone, v))
}

// BuyerPhoneIn applies the In predicate on the "buyer_phone" field.
func BuyerPhoneIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneNotIn applies the NotIn predicate on the "buyer_phone" field.
func BuyerPhoneNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerPhone, vs...))
}

// BuyerPhoneGT applies the GT predicate on the "buyer_phone" field.
func BuyerPhoneGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerPhone, v))
}

// BuyerPhoneGTE applies the GTE predicate on the "buyer_phone" field.
func BuyerPhoneGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerPhone, v))
}

// BuyerPhoneLT applies the LT predicate on the "buyer_phone" field.
func BuyerPhoneLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerPhone, v))
}

// BuyerPhoneLTE applies the LTE predicate on the "buyer_phone" field.
func BuyerPhoneLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerPhone, v))
}

// BuyerPhoneContains applies the Contains predicate on the "buyer_phone" field.
func BuyerPhoneContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerPhone, v))
}

// BuyerPhoneHasPrefix applies the HasPrefix predicate on the "buyer_phone" field.
func BuyerPhoneHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerPhone, v))
}

// BuyerPhoneHasSuffix applies the HasSuffix predicate on the "buyer_phone" field.
func BuyerPhoneHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerPhone, v))
}

// BuyerPhoneEqualFold applies the EqualFold predicate on the "buyer_phone" field.
func BuyerPhoneEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerPhone, v))
}

// BuyerPhoneContainsFold applies the ContainsFold predicate on the "buyer_phone" field.
func BuyerPhoneContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerPhone, v))
}

// BuyerAddressEQ applies the EQ predicate on the "buyer_address" field.
func BuyerAddressEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerAddress, v))
}

// BuyerAddressNEQ applies the NEQ predicate on the "buyer_address" field.
func BuyerAddressNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerAddress, v))
}

// BuyerAddressIn applies the In predicate on the "buyer_address" field.
func BuyerAddressIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerAddress, vs...))
}

// BuyerAddressNotIn applies the NotIn predicate on the "buyer_address" field.
func BuyerAddressNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerAddress, vs...))
}

// BuyerAddressGT applies the GT predicate on the "buyer_address" field.
func BuyerAddressGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerAddress, v))
}

// BuyerAddressGTE applies the GTE predicate on the "buyer_address" field.
func BuyerAddressGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerAddress, v))
}

// BuyerAddressLT applies the LT predicate on the "buyer_address" field.
func BuyerAddressLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerAddress, v))
}

// BuyerAddressLTE applies the LTE predicate on the "buyer_address" field.
func BuyerAddressLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerAddress, v))
}

// BuyerAddressContains applies the Contains predicate on the "buyer_address" field.
func BuyerAddressContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerAddress, v))
}

// BuyerAddressHasPrefix applies the HasPrefix predicate on the "buyer_address" field.
func BuyerAddressHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerAddress, v))
}

// BuyerAddressHasSuffix applies the HasSuffix predicate on the "buyer_address" field.
func BuyerAddressHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerAddress, v))
}

// BuyerAddressEqualFold applies the EqualFold predicate on the "buyer_address" field.
func BuyerAddressEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerAddress, v))
}

// BuyerAddressContainsFold applies the ContainsFold predicate on the "buyer_address" field.
func BuyerAddressContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerAddress, v))
}

// BuyerBankNameEQ applies the EQ predicate on the "buyer_bank_name" field.
func BuyerBankNameEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerBankName, v))
}

// BuyerBankNameNEQ applies the NEQ predicate on the "buyer_bank_name" field.
func BuyerBankNameNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerBankName, v))
}

// BuyerBankNameIn applies the In predicate on the "buyer_bank_name" field.
func BuyerBankNameIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerBankName, vs...))
}

// BuyerBankNameNotIn applies the NotIn predicate on the "buyer_bank_name" field.
func BuyerBankNameNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerBankName, vs...))
}

// BuyerBankNameGT applies the GT predicate on the "buyer_bank_name" field.
func BuyerBankNameGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerBankName, v))
}

// BuyerBankNameGTE applies the GTE predicate on the "buyer_bank_name" field.
func BuyerBankNameGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerBankName, v))
}

// BuyerBankNameLT applies the LT predicate on the "buyer_bank_name" field.
func BuyerBankNameLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerBankName, v))
}

// BuyerBankNameLTE applies the LTE predicate on the "buyer_bank_name" field.
func BuyerBankNameLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerBankName, v))
}

// BuyerBankNameContains applies the Contains predicate on the "buyer_bank_name" field.
func BuyerBankNameContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerBankName, v))
}

// BuyerBankNameHasPrefix applies the HasPrefix predicate on the "buyer_bank_name" field.
func BuyerBankNameHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerBankName, v))
}

// BuyerBankNameHasSuffix applies the HasSuffix predicate on the "buyer_bank_name" field.
func BuyerBankNameHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerBankName, v))
}

// BuyerBankNameEqualFold applies the EqualFold predicate on the "buyer_bank_name" field.
func BuyerBankNameEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerBankName, v))
}

// BuyerBankNameContainsFold applies the ContainsFold predicate on the "buyer_bank_name" field.
func BuyerBankNameContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerBankName, v))
}

// BuyerBankAccountEQ applies the EQ predicate on the "buyer_bank_account" field.
func BuyerBankAccountEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldBuyerBankAccount, v))
}

// BuyerBankAccountNEQ applies the NEQ predicate on the "buyer_bank_account" field.
func BuyerBankAccountNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldBuyerBankAccount, v))
}

// BuyerBankAccountIn applies the In predicate on the "buyer_bank_account" field.
func BuyerBankAccountIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldBuyerBankAccount, vs...))
}

// BuyerBankAccountNotIn applies the NotIn predicate on the "buyer_bank_account" field.
func BuyerBankAccountNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldBuyerBankAccount, vs...))
}

// BuyerBankAccountGT applies the GT predicate on the "buyer_bank_account" field.
func BuyerBankAccountGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldBuyerBankAccount, v))
}

// BuyerBankAccountGTE applies the GTE predicate on the "buyer_bank_account" field.
func BuyerBankAccountGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldBuyerBankAccount, v))
}

// BuyerBankAccountLT applies the LT predicate on the "buyer_bank_account" field.
func BuyerBankAccountLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldBuyerBankAccount, v))
}

// BuyerBankAccountLTE applies the LTE predicate on the "buyer_bank_account" field.
func BuyerBankAccountLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldBuyerBankAccount, v))
}

// BuyerBankAccountContains applies the Contains predicate on the "buyer_bank_account" field.
func BuyerBankAccountContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldBuyerBankAccount, v))
}

// BuyerBankAccountHasPrefix applies the HasPrefix predicate on the "buyer_bank_account" field.
func BuyerBankAccountHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldBuyerBankAccount, v))
}

// BuyerBankAccountHasSuffix applies the HasSuffix predicate on the "buyer_bank_account" field.
func BuyerBankAccountHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldBuyerBankAccount, v))
}

// BuyerBankAccountEqualFold applies the EqualFold predicate on the "buyer_bank_account" field.
func BuyerBankAccountEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldBuyerBankAccount, v))
}

// BuyerBankAccountContainsFold applies the ContainsFold predicate on the "buyer_bank_account" field.
func BuyerBankAccountContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldBuyerBankAccount, v))
}

// InvoiceAmountEQ applies the EQ predicate on the "invoice_amount" field.
func InvoiceAmountEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountNEQ applies the NEQ predicate on the "invoice_amount" field.
func InvoiceAmountNEQ(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountIn applies the In predicate on the "invoice_amount" field.
func InvoiceAmountIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountNotIn applies the NotIn predicate on the "invoice_amount" field.
func InvoiceAmountNotIn(vs ...float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountGT applies the GT predicate on the "invoice_amount" field.
func InvoiceAmountGT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceAmount, v))
}

// InvoiceAmountGTE applies the GTE predicate on the "invoice_amount" field.
func InvoiceAmountGTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceAmount, v))
}

// InvoiceAmountLT applies the LT predicate on the "invoice_amount" field.
func InvoiceAmountLT(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceAmount, v))
}

// InvoiceAmountLTE applies the LTE predicate on the "invoice_amount" field.
func InvoiceAmountLTE(v float64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceAmount, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// InvoiceTypeGT applies the GT predicate on the "invoice_type" field.
func InvoiceTypeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceType, v))
}

// InvoiceTypeGTE applies the GTE predicate on the "invoice_type" field.
func InvoiceTypeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceType, v))
}

// InvoiceTypeLT applies the LT predicate on the "invoice_type" field.
func InvoiceTypeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceType, v))
}

// InvoiceTypeLTE applies the LTE predicate on the "invoice_type" field.
func InvoiceTypeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceType, v))
}

// InvoiceTypeContains applies the Contains predicate on the "invoice_type" field.
func InvoiceTypeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldInvoiceType, v))
}

// InvoiceTypeHasPrefix applies the HasPrefix predicate on the "invoice_type" field.
func InvoiceTypeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldInvoiceType, v))
}

// InvoiceTypeHasSuffix applies the HasSuffix predicate on the "invoice_type" field.
func InvoiceTypeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldInvoiceType, v))
}

// InvoiceTypeEqualFold applies the EqualFold predicate on the "invoice_type" field.
func InvoiceTypeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldInvoiceType, v))
}

// InvoiceTypeContainsFold applies the ContainsFold predicate on the "invoice_type" field.
func InvoiceTypeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldInvoiceType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldContent, v))
}

// TaxRateEQ applies the EQ predicate on the "tax_rate" field.
func TaxRateEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxRate, v))
}

// TaxRateNEQ applies the NEQ predicate on the "tax_rate" field.
func TaxRateNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTaxRate, v))
}

// TaxRateIn applies the In predicate on the "tax_rate" field.
func TaxRateIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTaxRate, vs...))
}

// TaxRateNotIn applies the NotIn predicate on the "tax_rate" field.
func TaxRateNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTaxRate, vs...))
}

// TaxRateGT applies the GT predicate on the "tax_rate" field.
func TaxRateGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTaxRate, v))
}

// TaxRateGTE applies the GTE predicate on the "tax_rate" field.
func TaxRateGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTaxRate, v))
}

// TaxRateLT applies the LT predicate on the "tax_rate" field.
func TaxRateLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTaxRate, v))
}

// TaxRateLTE applies the LTE predicate on the "tax_rate" field.
func TaxRateLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTaxRate, v))
}

// TaxRateContains applies the Contains predicate on the "tax_rate" field.
func TaxRateContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldTaxRate, v))
}

// TaxRateHasPrefix applies the HasPrefix predicate on the "tax_rate" field.
func TaxRateHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldTaxRate, v))
}

// TaxRateHasSuffix applies the HasSuffix predicate on the "tax_rate" field.
func TaxRateHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldTaxRate, v))
}

// TaxRateEqualFold applies the EqualFold predicate on the "tax_rate" field.
func TaxRateEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldTaxRate, v))
}

// TaxRateContainsFold applies the ContainsFold predicate on the "tax_rate" field.
func TaxRateContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldTaxRate, v))
}

// TaxClassificationCodeEQ applies the EQ predicate on the "tax_classification_code" field.
func TaxClassificationCodeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeNEQ applies the NEQ predicate on the "tax_classification_code" field.
func TaxClassificationCodeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeIn applies the In predicate on the "tax_classification_code" field.
func TaxClassificationCodeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTaxClassificationCode, vs...))
}

// TaxClassificationCodeNotIn applies the NotIn predicate on the "tax_classification_code" field.
func TaxClassificationCodeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTaxClassificationCode, vs...))
}

// TaxClassificationCodeGT applies the GT predicate on the "tax_classification_code" field.
func TaxClassificationCodeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeGTE applies the GTE predicate on the "tax_classification_code" field.
func TaxClassificationCodeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeLT applies the LT predicate on the "tax_classification_code" field.
func TaxClassificationCodeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeLTE applies the LTE predicate on the "tax_classification_code" field.
func TaxClassificationCodeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeContains applies the Contains predicate on the "tax_classification_code" field.
func TaxClassificationCodeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeHasPrefix applies the HasPrefix predicate on the "tax_classification_code" field.
func TaxClassificationCodeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeHasSuffix applies the HasSuffix predicate on the "tax_classification_code" field.
func TaxClassificationCodeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeEqualFold applies the EqualFold predicate on the "tax_classification_code" field.
func TaxClassificationCodeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldTaxClassificationCode, v))
}

// TaxClassificationCodeContainsFold applies the ContainsFold predicate on the "tax_classification_code" field.
func TaxClassificationCodeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldTaxClassificationCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldStatus, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderOrderIDEQ applies the EQ predicate on the "provider_order_id" field.
func ProviderOrderIDEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProviderOrderID, v))
}

// ProviderOrderIDNEQ applies the NEQ predicate on the "provider_order_id" field.
func ProviderOrderIDNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldProviderOrderID, v))
}

// ProviderOrderIDIn applies the In predicate on the "provider_order_id" field.
func ProviderOrderIDIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldProviderOrderID, vs...))
}

// ProviderOrderIDNotIn applies the NotIn predicate on the "provider_order_id" field.
func ProviderOrderIDNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldProviderOrderID, vs...))
}

// ProviderOrderIDGT applies the GT predicate on the "provider_order_id" field.
func ProviderOrderIDGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldProviderOrderID, v))
}

// ProviderOrderIDGTE applies the GTE predicate on the "provider_order_id" field.
func ProviderOrderIDGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldProviderOrderID, v))
}

// ProviderOrderIDLT applies the LT predicate on the "provider_order_id" field.
func ProviderOrderIDLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldProviderOrderID, v))
}

// ProviderOrderIDLTE applies the LTE predicate on the "provider_order_id" field.
func ProviderOrderIDLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldProviderOrderID, v))
}

// ProviderOrderIDContains applies the Contains predicate on the "provider_order_id" field.
func ProviderOrderIDContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldProviderOrderID, v))
}

// ProviderOrderIDHasPrefix applies the HasPrefix predicate on the "provider_order_id" field.
func ProviderOrderIDHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldProviderOrderID, v))
}

// ProviderOrderIDHasSuffix applies the HasSuffix predicate on the "provider_order_id" field.
func ProviderOrderIDHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldProviderOrderID, v))
}

// ProviderOrderIDEqualFold applies the EqualFold predicate on the "provider_order_id" field.
func ProviderOrderIDEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldProviderOrderID, v))
}

// ProviderOrderIDContainsFold applies the ContainsFold predicate on the "provider_order_id" field.
func ProviderOrderIDContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldProviderOrderID, v))
}

// ProviderOrderNoEQ applies the EQ predicate on the "provider_order_no" field.
func ProviderOrderNoEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldProviderOrderNo, v))
}

// ProviderOrderNoNEQ applies the NEQ predicate on the "provider_order_no" field.
func ProviderOrderNoNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldProviderOrderNo, v))
}

// ProviderOrderNoIn applies the In predicate on the "provider_order_no" field.
func ProviderOrderNoIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldProviderOrderNo, vs...))
}

// ProviderOrderNoNotIn applies the NotIn predicate on the "provider_order_no" field.
func ProviderOrderNoNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldProviderOrderNo, vs...))
}

// ProviderOrderNoGT applies the GT predicate on the "provider_order_no" field.
func ProviderOrderNoGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldProviderOrderNo, v))
}

// ProviderOrderNoGTE applies the GTE predicate on the "provider_order_no" field.
func ProviderOrderNoGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldProviderOrderNo, v))
}

// ProviderOrderNoLT applies the LT predicate on the "provider_order_no" field.
func ProviderOrderNoLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldProviderOrderNo, v))
}

// ProviderOrderNoLTE applies the LTE predicate on the "provider_order_no" field.
func ProviderOrderNoLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldProviderOrderNo, v))
}

// ProviderOrderNoContains applies the Contains predicate on the "provider_order_no" field.
func ProviderOrderNoContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldProviderOrderNo, v))
}

// ProviderOrderNoHasPrefix applies the HasPrefix predicate on the "provider_order_no" field.
func ProviderOrderNoHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldProviderOrderNo, v))
}

// ProviderOrderNoHasSuffix applies the HasSuffix predicate on the "provider_order_no" field.
func ProviderOrderNoHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldProviderOrderNo, v))
}

// ProviderOrderNoEqualFold applies the EqualFold predicate on the "provider_order_no" field.
func ProviderOrderNoEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldProviderOrderNo, v))
}

// ProviderOrderNoContainsFold applies the ContainsFold predicate on the "provider_order_no" field.
func ProviderOrderNoContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldProviderOrderNo, v))
}

// InvoiceCodeEQ applies the EQ predicate on the "invoice_code" field.
func InvoiceCodeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceCode, v))
}

// InvoiceCodeNEQ applies the NEQ predicate on the "invoice_code" field.
func InvoiceCodeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceCode, v))
}

// InvoiceCodeIn applies the In predicate on the "invoice_code" field.
func InvoiceCodeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeNotIn applies the NotIn predicate on the "invoice_code" field.
func InvoiceCodeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeGT applies the GT predicate on the "invoice_code" field.
func InvoiceCodeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceCode, v))
}

// InvoiceCodeGTE applies the GTE predicate on the "invoice_code" field.
func InvoiceCodeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceCode, v))
}

// InvoiceCodeLT applies the LT predicate on the "invoice_code" field.
func InvoiceCodeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceCode, v))
}

// InvoiceCodeLTE applies the LTE predicate on the "invoice_code" field.
func InvoiceCodeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceCode, v))
}

// InvoiceCodeContains applies the Contains predicate on the "invoice_code" field.
func InvoiceCodeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldInvoiceCode, v))
}

// InvoiceCodeHasPrefix applies the HasPrefix predicate on the "invoice_code" field.
func InvoiceCodeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldInvoiceCode, v))
}

// InvoiceCodeHasSuffix applies the HasSuffix predicate on the "invoice_code" field.
func InvoiceCodeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldInvoiceCode, v))
}

// InvoiceCodeEqualFold applies the EqualFold predicate on the "invoice_code" field.
func InvoiceCodeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldInvoiceCode, v))
}

// InvoiceCodeContainsFold applies the ContainsFold predicate on the "invoice_code" field.
func InvoiceCodeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldInvoiceCode, v))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldIssuedAt))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// RequestPayloadSnapshotIsNil applies the IsNil predicate on the "request_payload_snapshot" field.
func RequestPayloadSnapshotIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRequestPayloadSnapshot))
}

// RequestPayloadSnapshotNotNil applies the NotNil predicate on the "request_payload_snapshot" field.
func RequestPayloadSnapshotNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRequestPayloadSnapshot))
}

// ResponsePayloadSnapshotIsNil applies the IsNil predicate on the "response_payload_snapshot" field.
func ResponsePayloadSnapshotIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldResponsePayloadSnapshot))
}

// ResponsePayloadSnapshotNotNil applies the NotNil predicate on the "response_payload_snapshot" field.
func ResponsePayloadSnapshotNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldResponsePayloadSnapshot))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRetryCount, v))
}

// PdfFileDataEQ applies the EQ predicate on the "pdf_file_data" field.
func PdfFileDataEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldPdfFileData, v))
}

// PdfFileDataNEQ applies the NEQ predicate on the "pdf_file_data" field.
func PdfFileDataNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldPdfFileData, v))
}

// PdfFileDataIn applies the In predicate on the "pdf_file_data" field.
func PdfFileDataIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldPdfFileData, vs...))
}

// PdfFileDataNotIn applies the NotIn predicate on the "pdf_file_data" field.
func PdfFileDataNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldPdfFileData, vs...))
}

// PdfFileDataGT applies the GT predicate on the "pdf_file_data" field.
func PdfFileDataGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldPdfFileData, v))
}

// PdfFileDataGTE applies the GTE predicate on the "pdf_file_data" field.
func PdfFileDataGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldPdfFileData, v))
}

// PdfFileDataLT applies the LT predicate on the "pdf_file_data" field.
func PdfFileDataLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldPdfFileData, v))
}

// PdfFileDataLTE applies the LTE predicate on the "pdf_file_data" field.
func PdfFileDataLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldPdfFileData, v))
}

// PdfFileDataContains applies the Contains predicate on the "pdf_file_data" field.
func PdfFileDataContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldPdfFileData, v))
}

// PdfFileDataHasPrefix applies the HasPrefix predicate on the "pdf_file_data" field.
func PdfFileDataHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldPdfFileData, v))
}

// PdfFileDataHasSuffix applies the HasSuffix predicate on the "pdf_file_data" field.
func PdfFileDataHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldPdfFileData, v))
}

// PdfFileDataEqualFold applies the EqualFold predicate on the "pdf_file_data" field.
func PdfFileDataEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldPdfFileData, v))
}

// PdfFileDataContainsFold applies the ContainsFold predicate on the "pdf_file_data" field.
func PdfFileDataContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldPdfFileData, v))
}

// OfdFileDataEQ applies the EQ predicate on the "ofd_file_data" field.
func OfdFileDataEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldOfdFileData, v))
}

// OfdFileDataNEQ applies the NEQ predicate on the "ofd_file_data" field.
func OfdFileDataNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldOfdFileData, v))
}

// OfdFileDataIn applies the In predicate on the "ofd_file_data" field.
func OfdFileDataIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldOfdFileData, vs...))
}

// OfdFileDataNotIn applies the NotIn predicate on the "ofd_file_data" field.
func OfdFileDataNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldOfdFileData, vs...))
}

// OfdFileDataGT applies the GT predicate on the "ofd_file_data" field.
func OfdFileDataGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldOfdFileData, v))
}

// OfdFileDataGTE applies the GTE predicate on the "ofd_file_data" field.
func OfdFileDataGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldOfdFileData, v))
}

// OfdFileDataLT applies the LT predicate on the "ofd_file_data" field.
func OfdFileDataLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldOfdFileData, v))
}

// OfdFileDataLTE applies the LTE predicate on the "ofd_file_data" field.
func OfdFileDataLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldOfdFileData, v))
}

// OfdFileDataContains applies the Contains predicate on the "ofd_file_data" field.
func OfdFileDataContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldOfdFileData, v))
}

// OfdFileDataHasPrefix applies the HasPrefix predicate on the "ofd_file_data" field.
func OfdFileDataHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldOfdFileData, v))
}

// OfdFileDataHasSuffix applies the HasSuffix predicate on the "ofd_file_data" field.
func OfdFileDataHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldOfdFileData, v))
}

// OfdFileDataEqualFold applies the EqualFold predicate on the "ofd_file_data" field.
func OfdFileDataEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldOfdFileData, v))
}

// OfdFileDataContainsFold applies the ContainsFold predicate on the "ofd_file_data" field.
func OfdFileDataContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldOfdFileData, v))
}

// XMLFileDataEQ applies the EQ predicate on the "xml_file_data" field.
func XMLFileDataEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldXMLFileData, v))
}

// XMLFileDataNEQ applies the NEQ predicate on the "xml_file_data" field.
func XMLFileDataNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldXMLFileData, v))
}

// XMLFileDataIn applies the In predicate on the "xml_file_data" field.
func XMLFileDataIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldXMLFileData, vs...))
}

// XMLFileDataNotIn applies the NotIn predicate on the "xml_file_data" field.
func XMLFileDataNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldXMLFileData, vs...))
}

// XMLFileDataGT applies the GT predicate on the "xml_file_data" field.
func XMLFileDataGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldXMLFileData, v))
}

// XMLFileDataGTE applies the GTE predicate on the "xml_file_data" field.
func XMLFileDataGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldXMLFileData, v))
}

// XMLFileDataLT applies the LT predicate on the "xml_file_data" field.
func XMLFileDataLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldXMLFileData, v))
}

// XMLFileDataLTE applies the LTE predicate on the "xml_file_data" field.
func XMLFileDataLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldXMLFileData, v))
}

// XMLFileDataContains applies the Contains predicate on the "xml_file_data" field.
func XMLFileDataContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldXMLFileData, v))
}

// XMLFileDataHasPrefix applies the HasPrefix predicate on the "xml_file_data" field.
func XMLFileDataHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldXMLFileData, v))
}

// XMLFileDataHasSuffix applies the HasSuffix predicate on the "xml_file_data" field.
func XMLFileDataHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldXMLFileData, v))
}

// XMLFileDataEqualFold applies the EqualFold predicate on the "xml_file_data" field.
func XMLFileDataEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldXMLFileData, v))
}

// XMLFileDataContainsFold applies the ContainsFold predicate on the "xml_file_data" field.
func XMLFileDataContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldXMLFileData, v))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldSubmittedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.InvoiceApplicationOrder) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.NotPredicates(p))
}
