// Code generated by ent, DO NOT EDIT.

package invoiceapplicationorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoiceapplicationorder type in the database.
	Label = "invoice_application_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInvoiceApplicationID holds the string denoting the invoice_application_id field in the database.
	FieldInvoiceApplicationID = "invoice_application_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldOutTradeNo holds the string denoting the out_trade_no field in the database.
	FieldOutTradeNo = "out_trade_no"
	// FieldOrderType holds the string denoting the order_type field in the database.
	FieldOrderType = "order_type"
	// FieldOrderAmount holds the string denoting the order_amount field in the database.
	FieldOrderAmount = "order_amount"
	// FieldPayAmount holds the string denoting the pay_amount field in the database.
	FieldPayAmount = "pay_amount"
	// FieldRefundAmount holds the string denoting the refund_amount field in the database.
	FieldRefundAmount = "refund_amount"
	// FieldInvoiceAmount holds the string denoting the invoice_amount field in the database.
	FieldInvoiceAmount = "invoice_amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInvoiceApplication holds the string denoting the invoice_application edge name in mutations.
	EdgeInvoiceApplication = "invoice_application"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePaymentOrder holds the string denoting the payment_order edge name in mutations.
	EdgePaymentOrder = "payment_order"
	// Table holds the table name of the invoiceapplicationorder in the database.
	Table = "invoice_application_orders"
	// InvoiceApplicationTable is the table that holds the invoice_application relation/edge.
	InvoiceApplicationTable = "invoice_application_orders"
	// InvoiceApplicationInverseTable is the table name for the InvoiceApplication entity.
	// It exists in this package in order to avoid circular dependency with the "invoiceapplication" package.
	InvoiceApplicationInverseTable = "invoice_applications"
	// InvoiceApplicationColumn is the table column denoting the invoice_application relation/edge.
	InvoiceApplicationColumn = "invoice_application_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_application_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PaymentOrderTable is the table that holds the payment_order relation/edge.
	PaymentOrderTable = "invoice_application_orders"
	// PaymentOrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	PaymentOrderInverseTable = "payment_orders"
	// PaymentOrderColumn is the table column denoting the payment_order relation/edge.
	PaymentOrderColumn = "payment_order_id"
)

// Columns holds all SQL columns for invoiceapplicationorder fields.
var Columns = []string{
	FieldID,
	FieldInvoiceApplicationID,
	FieldUserID,
	FieldPaymentOrderID,
	FieldOutTradeNo,
	FieldOrderType,
	FieldOrderAmount,
	FieldPayAmount,
	FieldRefundAmount,
	FieldInvoiceAmount,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOutTradeNo holds the default value on creation for the "out_trade_no" field.
	DefaultOutTradeNo string
	// OutTradeNoValidator is a validator for the "out_trade_no" field. It is called by the builders before save.
	OutTradeNoValidator func(string) error
	// DefaultOrderType holds the default value on creation for the "order_type" field.
	DefaultOrderType string
	// OrderTypeValidator is a validator for the "order_type" field. It is called by the builders before save.
	OrderTypeValidator func(string) error
	// DefaultOrderAmount holds the default value on creation for the "order_amount" field.
	DefaultOrderAmount float64
	// DefaultPayAmount holds the default value on creation for the "pay_amount" field.
	DefaultPayAmount float64
	// DefaultRefundAmount holds the default value on creation for the "refund_amount" field.
	DefaultRefundAmount float64
	// DefaultInvoiceAmount holds the default value on creation for the "invoice_amount" field.
	DefaultInvoiceAmount float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplicationOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInvoiceApplicationID orders the results by the invoice_application_id field.
func ByInvoiceApplicationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceApplicationID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByOutTradeNo orders the results by the out_trade_no field.
func ByOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutTradeNo, opts...).ToFunc()
}

// ByOrderType orders the results by the order_type field.
func ByOrderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderType, opts...).ToFunc()
}

// ByOrderAmount orders the results by the order_amount field.
func ByOrderAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderAmount, opts...).ToFunc()
}

// ByPayAmount orders the results by the pay_amount field.
func ByPayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayAmount, opts...).ToFunc()
}

// ByRefundAmount orders the results by the refund_amount field.
func ByRefundAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAmount, opts...).ToFunc()
}

// ByInvoiceAmount orders the results by the invoice_amount field.
func ByInvoiceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceAmount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInvoiceApplicationField orders the results by invoice_application field.
func ByInvoiceApplicationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvoiceApplicationStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPaymentOrderField orders the results by payment_order field.
func ByPaymentOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPaymentOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newInvoiceApplicationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvoiceApplicationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InvoiceApplicationTable, InvoiceApplicationColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPaymentOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PaymentOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PaymentOrderTable, PaymentOrderColumn),
	)
}
