// Code generated by ent, DO NOT EDIT.

package invoiceapplicationorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldID, id))
}

// InvoiceApplicationID applies equality check predicate on the "invoice_application_id" field. It's identical to InvoiceApplicationIDEQ.
func InvoiceApplicationID(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldInvoiceApplicationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldUserID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldPaymentOrderID, v))
}

// OutTradeNo applies equality check predicate on the "out_trade_no" field. It's identical to OutTradeNoEQ.
func OutTradeNo(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOutTradeNo, v))
}

// OrderType applies equality check predicate on the "order_type" field. It's identical to OrderTypeEQ.
func OrderType(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOrderType, v))
}

// OrderAmount applies equality check predicate on the "order_amount" field. It's identical to OrderAmountEQ.
func OrderAmount(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOrderAmount, v))
}

// PayAmount applies equality check predicate on the "pay_amount" field. It's identical to PayAmountEQ.
func PayAmount(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldPayAmount, v))
}

// RefundAmount applies equality check predicate on the "refund_amount" field. It's identical to RefundAmountEQ.
func RefundAmount(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldRefundAmount, v))
}

// InvoiceAmount applies equality check predicate on the "invoice_amount" field. It's identical to InvoiceAmountEQ.
func InvoiceAmount(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldInvoiceAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceApplicationIDEQ applies the EQ predicate on the "invoice_application_id" field.
func InvoiceApplicationIDEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldInvoiceApplicationID, v))
}

// InvoiceApplicationIDNEQ applies the NEQ predicate on the "invoice_application_id" field.
func InvoiceApplicationIDNEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldInvoiceApplicationID, v))
}

// InvoiceApplicationIDIn applies the In predicate on the "invoice_application_id" field.
func InvoiceApplicationIDIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldInvoiceApplicationID, vs...))
}

// InvoiceApplicationIDNotIn applies the NotIn predicate on the "invoice_application_id" field.
func InvoiceApplicationIDNotIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldInvoiceApplicationID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// OutTradeNoEQ applies the EQ predicate on the "out_trade_no" field.
func OutTradeNoEQ(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOutTradeNo, v))
}

// OutTradeNoNEQ applies the NEQ predicate on the "out_trade_no" field.
func OutTradeNoNEQ(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldOutTradeNo, v))
}

// OutTradeNoIn applies the In predicate on the "out_trade_no" field.
func OutTradeNoIn(vs ...string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldOutTradeNo, vs...))
}

// OutTradeNoNotIn applies the NotIn predicate on the "out_trade_no" field.
func OutTradeNoNotIn(vs ...string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldOutTradeNo, vs...))
}

// OutTradeNoGT applies the GT predicate on the "out_trade_no" field.
func OutTradeNoGT(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldOutTradeNo, v))
}

// OutTradeNoGTE applies the GTE predicate on the "out_trade_no" field.
func OutTradeNoGTE(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldOutTradeNo, v))
}

// OutTradeNoLT applies the LT predicate on the "out_trade_no" field.
func OutTradeNoLT(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldOutTradeNo, v))
}

// OutTradeNoLTE applies the LTE predicate on the "out_trade_no" field.
func OutTradeNoLTE(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldOutTradeNo, v))
}

// OutTradeNoContains applies the Contains predicate on the "out_trade_no" field.
func OutTradeNoContains(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldContains(FieldOutTradeNo, v))
}

// OutTradeNoHasPrefix applies the HasPrefix predicate on the "out_trade_no" field.
func OutTradeNoHasPrefix(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldHasPrefix(FieldOutTradeNo, v))
}

// OutTradeNoHasSuffix applies the HasSuffix predicate on the "out_trade_no" field.
func OutTradeNoHasSuffix(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldHasSuffix(FieldOutTradeNo, v))
}

// OutTradeNoEqualFold applies the EqualFold predicate on the "out_trade_no" field.
func OutTradeNoEqualFold(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEqualFold(FieldOutTradeNo, v))
}

// OutTradeNoContainsFold applies the ContainsFold predicate on the "out_trade_no" field.
func OutTradeNoContainsFold(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldContainsFold(FieldOutTradeNo, v))
}

// OrderTypeEQ applies the EQ predicate on the "order_type" field.
func OrderTypeEQ(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOrderType, v))
}

// OrderTypeNEQ applies the NEQ predicate on the "order_type" field.
func OrderTypeNEQ(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldOrderType, v))
}

// OrderTypeIn applies the In predicate on the "order_type" field.
func OrderTypeIn(vs ...string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldOrderType, vs...))
}

// OrderTypeNotIn applies the NotIn predicate on the "order_type" field.
func OrderTypeNotIn(vs ...string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldOrderType, vs...))
}

// OrderTypeGT applies the GT predicate on the "order_type" field.
func OrderTypeGT(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldOrderType, v))
}

// OrderTypeGTE applies the GTE predicate on the "order_type" field.
func OrderTypeGTE(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldOrderType, v))
}

// OrderTypeLT applies the LT predicate on the "order_type" field.
func OrderTypeLT(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldOrderType, v))
}

// OrderTypeLTE applies the LTE predicate on the "order_type" field.
func OrderTypeLTE(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldOrderType, v))
}

// OrderTypeContains applies the Contains predicate on the "order_type" field.
func OrderTypeContains(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldContains(FieldOrderType, v))
}

// OrderTypeHasPrefix applies the HasPrefix predicate on the "order_type" field.
func OrderTypeHasPrefix(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldHasPrefix(FieldOrderType, v))
}

// OrderTypeHasSuffix applies the HasSuffix predicate on the "order_type" field.
func OrderTypeHasSuffix(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldHasSuffix(FieldOrderType, v))
}

// OrderTypeEqualFold applies the EqualFold predicate on the "order_type" field.
func OrderTypeEqualFold(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEqualFold(FieldOrderType, v))
}

// OrderTypeContainsFold applies the ContainsFold predicate on the "order_type" field.
func OrderTypeContainsFold(v string) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldContainsFold(FieldOrderType, v))
}

// OrderAmountEQ applies the EQ predicate on the "order_amount" field.
func OrderAmountEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldOrderAmount, v))
}

// OrderAmountNEQ applies the NEQ predicate on the "order_amount" field.
func OrderAmountNEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldOrderAmount, v))
}

// OrderAmountIn applies the In predicate on the "order_amount" field.
func OrderAmountIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldOrderAmount, vs...))
}

// OrderAmountNotIn applies the NotIn predicate on the "order_amount" field.
func OrderAmountNotIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldOrderAmount, vs...))
}

// OrderAmountGT applies the GT predicate on the "order_amount" field.
func OrderAmountGT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldOrderAmount, v))
}

// OrderAmountGTE applies the GTE predicate on the "order_amount" field.
func OrderAmountGTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldOrderAmount, v))
}

// OrderAmountLT applies the LT predicate on the "order_amount" field.
func OrderAmountLT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldOrderAmount, v))
}

// OrderAmountLTE applies the LTE predicate on the "order_amount" field.
func OrderAmountLTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldOrderAmount, v))
}

// PayAmountEQ applies the EQ predicate on the "pay_amount" field.
func PayAmountEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldPayAmount, v))
}

// PayAmountNEQ applies the NEQ predicate on the "pay_amount" field.
func PayAmountNEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldPayAmount, v))
}

// PayAmountIn applies the In predicate on the "pay_amount" field.
func PayAmountIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldPayAmount, vs...))
}

// PayAmountNotIn applies the NotIn predicate on the "pay_amount" field.
func PayAmountNotIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldPayAmount, vs...))
}

// PayAmountGT applies the GT predicate on the "pay_amount" field.
func PayAmountGT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldPayAmount, v))
}

// PayAmountGTE applies the GTE predicate on the "pay_amount" field.
func PayAmountGTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldPayAmount, v))
}

// PayAmountLT applies the LT predicate on the "pay_amount" field.
func PayAmountLT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldPayAmount, v))
}

// PayAmountLTE applies the LTE predicate on the "pay_amount" field.
func PayAmountLTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldPayAmount, v))
}

// RefundAmountEQ applies the EQ predicate on the "refund_amount" field.
func RefundAmountEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldRefundAmount, v))
}

// RefundAmountNEQ applies the NEQ predicate on the "refund_amount" field.
func RefundAmountNEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldRefundAmount, v))
}

// RefundAmountIn applies the In predicate on the "refund_amount" field.
func RefundAmountIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldRefundAmount, vs...))
}

// RefundAmountNotIn applies the NotIn predicate on the "refund_amount" field.
func RefundAmountNotIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldRefundAmount, vs...))
}

// RefundAmountGT applies the GT predicate on the "refund_amount" field.
func RefundAmountGT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldRefundAmount, v))
}

// RefundAmountGTE applies the GTE predicate on the "refund_amount" field.
func RefundAmountGTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldRefundAmount, v))
}

// RefundAmountLT applies the LT predicate on the "refund_amount" field.
func RefundAmountLT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldRefundAmount, v))
}

// RefundAmountLTE applies the LTE predicate on the "refund_amount" field.
func RefundAmountLTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldRefundAmount, v))
}

// InvoiceAmountEQ applies the EQ predicate on the "invoice_amount" field.
func InvoiceAmountEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountNEQ applies the NEQ predicate on the "invoice_amount" field.
func InvoiceAmountNEQ(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountIn applies the In predicate on the "invoice_amount" field.
func InvoiceAmountIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountNotIn applies the NotIn predicate on the "invoice_amount" field.
func InvoiceAmountNotIn(vs ...float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountGT applies the GT predicate on the "invoice_amount" field.
func InvoiceAmountGT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldInvoiceAmount, v))
}

// InvoiceAmountGTE applies the GTE predicate on the "invoice_amount" field.
func InvoiceAmountGTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldInvoiceAmount, v))
}

// InvoiceAmountLT applies the LT predicate on the "invoice_amount" field.
func InvoiceAmountLT(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldInvoiceAmount, v))
}

// InvoiceAmountLTE applies the LTE predicate on the "invoice_amount" field.
func InvoiceAmountLTE(v float64) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldInvoiceAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInvoiceApplication applies the HasEdge predicate on the "invoice_application" edge.
func HasInvoiceApplication() predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InvoiceApplicationTable, InvoiceApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvoiceApplicationWith applies the HasEdge predicate on the "invoice_application" edge with a given conditions (other predicates).
func HasInvoiceApplicationWith(preds ...predicate.InvoiceApplication) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := newInvoiceApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentOrder applies the HasEdge predicate on the "payment_order" edge.
func HasPaymentOrder() predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PaymentOrderTable, PaymentOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentOrderWith applies the HasEdge predicate on the "payment_order" edge with a given conditions (other predicates).
func HasPaymentOrderWith(preds ...predicate.PaymentOrder) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(func(s *sql.Selector) {
		step := newPaymentOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplicationOrder) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplicationOrder) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplicationOrder) predicate.InvoiceApplicationOrder {
	return predicate.InvoiceApplicationOrder(sql.NotPredicates(p))
}
