// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationCreate is the builder for creating a InvoiceApplication entity.
type InvoiceApplicationCreate struct {
	config
	mutation *InvoiceApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceApplicationCreate) SetUserID(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *InvoiceApplicationCreate) SetUserEmail(v string) *InvoiceApplicationCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableUserEmail(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetBuyerType sets the "buyer_type" field.
func (_c *InvoiceApplicationCreate) SetBuyerType(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerType(v)
	return _c
}

// SetNillableBuyerType sets the "buyer_type" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerType(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerType(*v)
	}
	return _c
}

// SetBuyerName sets the "buyer_name" field.
func (_c *InvoiceApplicationCreate) SetBuyerName(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerName(v)
	return _c
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (_c *InvoiceApplicationCreate) SetBuyerTaxNo(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerTaxNo(v)
	return _c
}

// SetNillableBuyerTaxNo sets the "buyer_tax_no" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerTaxNo(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerTaxNo(*v)
	}
	return _c
}

// SetBuyerEmail sets the "buyer_email" field.
func (_c *InvoiceApplicationCreate) SetBuyerEmail(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerEmail(v)
	return _c
}

// SetNillableBuyerEmail sets the "buyer_email" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerEmail(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerEmail(*v)
	}
	return _c
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_c *InvoiceApplicationCreate) SetBuyerPhone(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerPhone(v)
	return _c
}

// SetNillableBuyerPhone sets the "buyer_phone" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerPhone(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerPhone(*v)
	}
	return _c
}

// SetBuyerAddress sets the "buyer_address" field.
func (_c *InvoiceApplicationCreate) SetBuyerAddress(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerAddress(v)
	return _c
}

// SetNillableBuyerAddress sets the "buyer_address" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerAddress(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerAddress(*v)
	}
	return _c
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (_c *InvoiceApplicationCreate) SetBuyerBankName(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerBankName(v)
	return _c
}

// SetNillableBuyerBankName sets the "buyer_bank_name" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerBankName(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerBankName(*v)
	}
	return _c
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (_c *InvoiceApplicationCreate) SetBuyerBankAccount(v string) *InvoiceApplicationCreate {
	_c.mutation.SetBuyerBankAccount(v)
	return _c
}

// SetNillableBuyerBankAccount sets the "buyer_bank_account" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableBuyerBankAccount(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetBuyerBankAccount(*v)
	}
	return _c
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_c *InvoiceApplicationCreate) SetInvoiceAmount(v float64) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceAmount(v)
	return _c
}

// SetInvoiceType sets the "invoice_type" field.
func (_c *InvoiceApplicationCreate) SetInvoiceType(v string) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceType(v)
	return _c
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoiceType(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoiceType(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *InvoiceApplicationCreate) SetContent(v string) *InvoiceApplicationCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableContent(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetTaxRate sets the "tax_rate" field.
func (_c *InvoiceApplicationCreate) SetTaxRate(v string) *InvoiceApplicationCreate {
	_c.mutation.SetTaxRate(v)
	return _c
}

// SetNillableTaxRate sets the "tax_rate" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableTaxRate(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetTaxRate(*v)
	}
	return _c
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (_c *InvoiceApplicationCreate) SetTaxClassificationCode(v string) *InvoiceApplicationCreate {
	_c.mutation.SetTaxClassificationCode(v)
	return _c
}

// SetNillableTaxClassificationCode sets the "tax_classification_code" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableTaxClassificationCode(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetTaxClassificationCode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceApplicationCreate) SetStatus(v string) *InvoiceApplicationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableStatus(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *InvoiceApplicationCreate) SetProvider(v string) *InvoiceApplicationCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableProvider(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_c *InvoiceApplicationCreate) SetProviderOrderID(v string) *InvoiceApplicationCreate {
	_c.mutation.SetProviderOrderID(v)
	return _c
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableProviderOrderID(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetProviderOrderID(*v)
	}
	return _c
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_c *InvoiceApplicationCreate) SetProviderOrderNo(v string) *InvoiceApplicationCreate {
	_c.mutation.SetProviderOrderNo(v)
	return _c
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableProviderOrderNo(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetProviderOrderNo(*v)
	}
	return _c
}

// SetInvoiceCode sets the "invoice_code" field.
func (_c *InvoiceApplicationCreate) SetInvoiceCode(v string) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceCode(v)
	return _c
}

// SetNillableInvoiceCode sets the "invoice_code" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoiceCode(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoiceCode(*v)
	}
	return _c
}

// SetInvoiceNo sets the "invoice_no" field.
func (_c *InvoiceApplicationCreate) SetInvoiceNo(v string) *InvoiceApplicationCreate {
	_c.mutation.SetInvoiceNo(v)
	return _c
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableInvoiceNo(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetInvoiceNo(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceApplicationCreate) SetIssuedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableIssuedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *InvoiceApplicationCreate) SetLastErrorCode(v string) *InvoiceApplicationCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableLastErrorCode(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_c *InvoiceApplicationCreate) SetLastErrorMessage(v string) *InvoiceApplicationCreate {
	_c.mutation.SetLastErrorMessage(v)
	return _c
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableLastErrorMessage(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetLastErrorMessage(*v)
	}
	return _c
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (_c *InvoiceApplicationCreate) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationCreate {
	_c.mutation.SetRequestPayloadSnapshot(v)
	return _c
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (_c *InvoiceApplicationCreate) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationCreate {
	_c.mutation.SetResponsePayloadSnapshot(v)
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *InvoiceApplicationCreate) SetRetryCount(v int) *InvoiceApplicationCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRetryCount(v *int) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetPdfFileData sets the "pdf_file_data" field.
func (_c *InvoiceApplicationCreate) SetPdfFileData(v string) *InvoiceApplicationCreate {
	_c.mutation.SetPdfFileData(v)
	return _c
}

// SetNillablePdfFileData sets the "pdf_file_data" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillablePdfFileData(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetPdfFileData(*v)
	}
	return _c
}

// SetOfdFileData sets the "ofd_file_data" field.
func (_c *InvoiceApplicationCreate) SetOfdFileData(v string) *InvoiceApplicationCreate {
	_c.mutation.SetOfdFileData(v)
	return _c
}

// SetNillableOfdFileData sets the "ofd_file_data" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableOfdFileData(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetOfdFileData(*v)
	}
	return _c
}

// SetXMLFileData sets the "xml_file_data" field.
func (_c *InvoiceApplicationCreate) SetXMLFileData(v string) *InvoiceApplicationCreate {
	_c.mutation.SetXMLFileData(v)
	return _c
}

// SetNillableXMLFileData sets the "xml_file_data" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableXMLFileData(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetXMLFileData(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *InvoiceApplicationCreate) SetSubmittedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableSubmittedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationCreate) SetCreatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceApplicationCreate) SetUpdatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceApplicationCreate) SetUser(v *User) *InvoiceApplicationCreate {
	return _c.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_c *InvoiceApplicationCreate) AddOrderIDs(ids ...int64) *InvoiceApplicationCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_c *InvoiceApplicationCreate) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_c *InvoiceApplicationCreate) Mutation() *InvoiceApplicationMutation {
	return _c.mutation
}

// Save creates the InvoiceApplication in the database.
func (_c *InvoiceApplicationCreate) Save(ctx context.Context) (*InvoiceApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationCreate) SaveX(ctx context.Context) *InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationCreate) defaults() {
	if _, ok := _c.mutation.UserEmail(); !ok {
		v := invoiceapplication.DefaultUserEmail
		_c.mutation.SetUserEmail(v)
	}
	if _, ok := _c.mutation.BuyerType(); !ok {
		v := invoiceapplication.DefaultBuyerType
		_c.mutation.SetBuyerType(v)
	}
	if _, ok := _c.mutation.BuyerTaxNo(); !ok {
		v := invoiceapplication.DefaultBuyerTaxNo
		_c.mutation.SetBuyerTaxNo(v)
	}
	if _, ok := _c.mutation.BuyerEmail(); !ok {
		v := invoiceapplication.DefaultBuyerEmail
		_c.mutation.SetBuyerEmail(v)
	}
	if _, ok := _c.mutation.BuyerPhone(); !ok {
		v := invoiceapplication.DefaultBuyerPhone
		_c.mutation.SetBuyerPhone(v)
	}
	if _, ok := _c.mutation.BuyerAddress(); !ok {
		v := invoiceapplication.DefaultBuyerAddress
		_c.mutation.SetBuyerAddress(v)
	}
	if _, ok := _c.mutation.BuyerBankName(); !ok {
		v := invoiceapplication.DefaultBuyerBankName
		_c.mutation.SetBuyerBankName(v)
	}
	if _, ok := _c.mutation.BuyerBankAccount(); !ok {
		v := invoiceapplication.DefaultBuyerBankAccount
		_c.mutation.SetBuyerBankAccount(v)
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		v := invoiceapplication.DefaultInvoiceType
		_c.mutation.SetInvoiceType(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := invoiceapplication.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.TaxRate(); !ok {
		v := invoiceapplication.DefaultTaxRate
		_c.mutation.SetTaxRate(v)
	}
	if _, ok := _c.mutation.TaxClassificationCode(); !ok {
		v := invoiceapplication.DefaultTaxClassificationCode
		_c.mutation.SetTaxClassificationCode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoiceapplication.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := invoiceapplication.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.ProviderOrderID(); !ok {
		v := invoiceapplication.DefaultProviderOrderID
		_c.mutation.SetProviderOrderID(v)
	}
	if _, ok := _c.mutation.ProviderOrderNo(); !ok {
		v := invoiceapplication.DefaultProviderOrderNo
		_c.mutation.SetProviderOrderNo(v)
	}
	if _, ok := _c.mutation.InvoiceCode(); !ok {
		v := invoiceapplication.DefaultInvoiceCode
		_c.mutation.SetInvoiceCode(v)
	}
	if _, ok := _c.mutation.InvoiceNo(); !ok {
		v := invoiceapplication.DefaultInvoiceNo
		_c.mutation.SetInvoiceNo(v)
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		v := invoiceapplication.DefaultLastErrorCode
		_c.mutation.SetLastErrorCode(v)
	}
	if _, ok := _c.mutation.LastErrorMessage(); !ok {
		v := invoiceapplication.DefaultLastErrorMessage
		_c.mutation.SetLastErrorMessage(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := invoiceapplication.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.PdfFileData(); !ok {
		v := invoiceapplication.DefaultPdfFileData
		_c.mutation.SetPdfFileData(v)
	}
	if _, ok := _c.mutation.OfdFileData(); !ok {
		v := invoiceapplication.DefaultOfdFileData
		_c.mutation.SetOfdFileData(v)
	}
	if _, ok := _c.mutation.XMLFileData(); !ok {
		v := invoiceapplication.DefaultXMLFileData
		_c.mutation.SetXMLFileData(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceApplication.user_id"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "InvoiceApplication.user_email"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := invoiceapplication.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.user_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerType(); !ok {
		return &ValidationError{Name: "buyer_type", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_type"`)}
	}
	if v, ok := _c.mutation.BuyerType(); ok {
		if err := invoiceapplication.BuyerTypeValidator(v); err != nil {
			return &ValidationError{Name: "buyer_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerName(); !ok {
		return &ValidationError{Name: "buyer_name", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_name"`)}
	}
	if v, ok := _c.mutation.BuyerName(); ok {
		if err := invoiceapplication.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerTaxNo(); !ok {
		return &ValidationError{Name: "buyer_tax_no", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_tax_no"`)}
	}
	if v, ok := _c.mutation.BuyerTaxNo(); ok {
		if err := invoiceapplication.BuyerTaxNoValidator(v); err != nil {
			return &ValidationError{Name: "buyer_tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_tax_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerEmail(); !ok {
		return &ValidationError{Name: "buyer_email", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_email"`)}
	}
	if v, ok := _c.mutation.BuyerEmail(); ok {
		if err := invoiceapplication.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerPhone(); !ok {
		return &ValidationError{Name: "buyer_phone", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_phone"`)}
	}
	if v, ok := _c.mutation.BuyerPhone(); ok {
		if err := invoiceapplication.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerAddress(); !ok {
		return &ValidationError{Name: "buyer_address", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_address"`)}
	}
	if _, ok := _c.mutation.BuyerBankName(); !ok {
		return &ValidationError{Name: "buyer_bank_name", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_bank_name"`)}
	}
	if v, ok := _c.mutation.BuyerBankName(); ok {
		if err := invoiceapplication.BuyerBankNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerBankAccount(); !ok {
		return &ValidationError{Name: "buyer_bank_account", err: errors.New(`ent: missing required field "InvoiceApplication.buyer_bank_account"`)}
	}
	if v, ok := _c.mutation.BuyerBankAccount(); ok {
		if err := invoiceapplication.BuyerBankAccountValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceAmount(); !ok {
		return &ValidationError{Name: "invoice_amount", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_amount"`)}
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		return &ValidationError{Name: "invoice_type", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_type"`)}
	}
	if v, ok := _c.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "InvoiceApplication.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := invoiceapplication.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxRate(); !ok {
		return &ValidationError{Name: "tax_rate", err: errors.New(`ent: missing required field "InvoiceApplication.tax_rate"`)}
	}
	if v, ok := _c.mutation.TaxRate(); ok {
		if err := invoiceapplication.TaxRateValidator(v); err != nil {
			return &ValidationError{Name: "tax_rate", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxClassificationCode(); !ok {
		return &ValidationError{Name: "tax_classification_code", err: errors.New(`ent: missing required field "InvoiceApplication.tax_classification_code"`)}
	}
	if v, ok := _c.mutation.TaxClassificationCode(); ok {
		if err := invoiceapplication.TaxClassificationCodeValidator(v); err != nil {
			return &ValidationError{Name: "tax_classification_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_classification_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceApplication.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "InvoiceApplication.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := invoiceapplication.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderOrderID(); !ok {
		return &ValidationError{Name: "provider_order_id", err: errors.New(`ent: missing required field "InvoiceApplication.provider_order_id"`)}
	}
	if v, ok := _c.mutation.ProviderOrderID(); ok {
		if err := invoiceapplication.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderOrderNo(); !ok {
		return &ValidationError{Name: "provider_order_no", err: errors.New(`ent: missing required field "InvoiceApplication.provider_order_no"`)}
	}
	if v, ok := _c.mutation.ProviderOrderNo(); ok {
		if err := invoiceapplication.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceCode(); !ok {
		return &ValidationError{Name: "invoice_code", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_code"`)}
	}
	if v, ok := _c.mutation.InvoiceCode(); ok {
		if err := invoiceapplication.InvoiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceNo(); !ok {
		return &ValidationError{Name: "invoice_no", err: errors.New(`ent: missing required field "InvoiceApplication.invoice_no"`)}
	}
	if v, ok := _c.mutation.InvoiceNo(); ok {
		if err := invoiceapplication.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		return &ValidationError{Name: "last_error_code", err: errors.New(`ent: missing required field "InvoiceApplication.last_error_code"`)}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := invoiceapplication.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.last_error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastErrorMessage(); !ok {
		return &ValidationError{Name: "last_error_message", err: errors.New(`ent: missing required field "InvoiceApplication.last_error_message"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "InvoiceApplication.retry_count"`)}
	}
	if _, ok := _c.mutation.PdfFileData(); !ok {
		return &ValidationError{Name: "pdf_file_data", err: errors.New(`ent: missing required field "InvoiceApplication.pdf_file_data"`)}
	}
	if _, ok := _c.mutation.OfdFileData(); !ok {
		return &ValidationError{Name: "ofd_file_data", err: errors.New(`ent: missing required field "InvoiceApplication.ofd_file_data"`)}
	}
	if _, ok := _c.mutation.XMLFileData(); !ok {
		return &ValidationError{Name: "xml_file_data", err: errors.New(`ent: missing required field "InvoiceApplication.xml_file_data"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceApplication.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceApplication.user"`)}
	}
	return nil
}

func (_c *InvoiceApplicationCreate) sqlSave(ctx context.Context) (*InvoiceApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationCreate) createSpec() (*InvoiceApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplication.Table, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(invoiceapplication.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.BuyerType(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerType, field.TypeString, value)
		_node.BuyerType = value
	}
	if value, ok := _c.mutation.BuyerName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerName, field.TypeString, value)
		_node.BuyerName = value
	}
	if value, ok := _c.mutation.BuyerTaxNo(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerTaxNo, field.TypeString, value)
		_node.BuyerTaxNo = value
	}
	if value, ok := _c.mutation.BuyerEmail(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerEmail, field.TypeString, value)
		_node.BuyerEmail = value
	}
	if value, ok := _c.mutation.BuyerPhone(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerPhone, field.TypeString, value)
		_node.BuyerPhone = value
	}
	if value, ok := _c.mutation.BuyerAddress(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerAddress, field.TypeString, value)
		_node.BuyerAddress = value
	}
	if value, ok := _c.mutation.BuyerBankName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankName, field.TypeString, value)
		_node.BuyerBankName = value
	}
	if value, ok := _c.mutation.BuyerBankAccount(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankAccount, field.TypeString, value)
		_node.BuyerBankAccount = value
	}
	if value, ok := _c.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceAmount, field.TypeFloat64, value)
		_node.InvoiceAmount = value
	}
	if value, ok := _c.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
		_node.InvoiceType = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(invoiceapplication.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.TaxRate(); ok {
		_spec.SetField(invoiceapplication.FieldTaxRate, field.TypeString, value)
		_node.TaxRate = value
	}
	if value, ok := _c.mutation.TaxClassificationCode(); ok {
		_spec.SetField(invoiceapplication.FieldTaxClassificationCode, field.TypeString, value)
		_node.TaxClassificationCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(invoiceapplication.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderOrderID(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderID, field.TypeString, value)
		_node.ProviderOrderID = value
	}
	if value, ok := _c.mutation.ProviderOrderNo(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderNo, field.TypeString, value)
		_node.ProviderOrderNo = value
	}
	if value, ok := _c.mutation.InvoiceCode(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceCode, field.TypeString, value)
		_node.InvoiceCode = value
	}
	if value, ok := _c.mutation.InvoiceNo(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNo, field.TypeString, value)
		_node.InvoiceNo = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoiceapplication.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = value
	}
	if value, ok := _c.mutation.LastErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorMessage, field.TypeString, value)
		_node.LastErrorMessage = value
	}
	if value, ok := _c.mutation.RequestPayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldRequestPayloadSnapshot, field.TypeJSON, value)
		_node.RequestPayloadSnapshot = value
	}
	if value, ok := _c.mutation.ResponsePayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldResponsePayloadSnapshot, field.TypeJSON, value)
		_node.ResponsePayloadSnapshot = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(invoiceapplication.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.PdfFileData(); ok {
		_spec.SetField(invoiceapplication.FieldPdfFileData, field.TypeString, value)
		_node.PdfFileData = value
	}
	if value, ok := _c.mutation.OfdFileData(); ok {
		_spec.SetField(invoiceapplication.FieldOfdFileData, field.TypeString, value)
		_node.OfdFileData = value
	}
	if value, ok := _c.mutation.XMLFileData(); ok {
		_spec.SetField(invoiceapplication.FieldXMLFileData, field.TypeString, value)
		_node.XMLFileData = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(invoiceapplication.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplication node.
	InvoiceApplicationUpsertOne struct {
		create *InvoiceApplicationCreate
	}

	// InvoiceApplicationUpsert is the "OnConflict" setter.
	InvoiceApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsert) SetUserID(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUserID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceApplicationUpsert) SetUserEmail(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUserEmail() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUserEmail)
	return u
}

// SetBuyerType sets the "buyer_type" field.
func (u *InvoiceApplicationUpsert) SetBuyerType(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerType, v)
	return u
}

// UpdateBuyerType sets the "buyer_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerType() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerType)
	return u
}

// SetBuyerName sets the "buyer_name" field.
func (u *InvoiceApplicationUpsert) SetBuyerName(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerName, v)
	return u
}

// UpdateBuyerName sets the "buyer_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerName() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerName)
	return u
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (u *InvoiceApplicationUpsert) SetBuyerTaxNo(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerTaxNo, v)
	return u
}

// UpdateBuyerTaxNo sets the "buyer_tax_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerTaxNo() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerTaxNo)
	return u
}

// SetBuyerEmail sets the "buyer_email" field.
func (u *InvoiceApplicationUpsert) SetBuyerEmail(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerEmail, v)
	return u
}

// UpdateBuyerEmail sets the "buyer_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerEmail() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerEmail)
	return u
}

// SetBuyerPhone sets the "buyer_phone" field.
func (u *InvoiceApplicationUpsert) SetBuyerPhone(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerPhone, v)
	return u
}

// UpdateBuyerPhone sets the "buyer_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerPhone() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerPhone)
	return u
}

// SetBuyerAddress sets the "buyer_address" field.
func (u *InvoiceApplicationUpsert) SetBuyerAddress(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerAddress, v)
	return u
}

// UpdateBuyerAddress sets the "buyer_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerAddress() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerAddress)
	return u
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (u *InvoiceApplicationUpsert) SetBuyerBankName(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerBankName, v)
	return u
}

// UpdateBuyerBankName sets the "buyer_bank_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerBankName() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerBankName)
	return u
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (u *InvoiceApplicationUpsert) SetBuyerBankAccount(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldBuyerBankAccount, v)
	return u
}

// UpdateBuyerBankAccount sets the "buyer_bank_account" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateBuyerBankAccount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldBuyerBankAccount)
	return u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationUpsert) SetInvoiceAmount(v float64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceAmount, v)
	return u
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceAmount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceAmount)
	return u
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationUpsert) AddInvoiceAmount(v float64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldInvoiceAmount, v)
	return u
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsert) SetInvoiceType(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceType, v)
	return u
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceType() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceType)
	return u
}

// SetContent sets the "content" field.
func (u *InvoiceApplicationUpsert) SetContent(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateContent() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldContent)
	return u
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceApplicationUpsert) SetTaxRate(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTaxRate, v)
	return u
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTaxRate() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTaxRate)
	return u
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (u *InvoiceApplicationUpsert) SetTaxClassificationCode(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTaxClassificationCode, v)
	return u
}

// UpdateTaxClassificationCode sets the "tax_classification_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTaxClassificationCode() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTaxClassificationCode)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsert) SetStatus(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateStatus() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldStatus)
	return u
}

// SetProvider sets the "provider" field.
func (u *InvoiceApplicationUpsert) SetProvider(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateProvider() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldProvider)
	return u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *InvoiceApplicationUpsert) SetProviderOrderID(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldProviderOrderID, v)
	return u
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateProviderOrderID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldProviderOrderID)
	return u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *InvoiceApplicationUpsert) SetProviderOrderNo(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldProviderOrderNo, v)
	return u
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateProviderOrderNo() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldProviderOrderNo)
	return u
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceApplicationUpsert) SetInvoiceCode(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceCode, v)
	return u
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceCode() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceCode)
	return u
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceApplicationUpsert) SetInvoiceNo(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldInvoiceNo, v)
	return u
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateInvoiceNo() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldInvoiceNo)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceApplicationUpsert) SetIssuedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateIssuedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceApplicationUpsert) ClearIssuedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldIssuedAt)
	return u
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *InvoiceApplicationUpsert) SetLastErrorCode(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldLastErrorCode, v)
	return u
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateLastErrorCode() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldLastErrorCode)
	return u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *InvoiceApplicationUpsert) SetLastErrorMessage(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldLastErrorMessage, v)
	return u
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateLastErrorMessage() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldLastErrorMessage)
	return u
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsert) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRequestPayloadSnapshot, v)
	return u
}

// UpdateRequestPayloadSnapshot sets the "request_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRequestPayloadSnapshot() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRequestPayloadSnapshot)
	return u
}

// ClearRequestPayloadSnapshot clears the value of the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsert) ClearRequestPayloadSnapshot() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRequestPayloadSnapshot)
	return u
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsert) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldResponsePayloadSnapshot, v)
	return u
}

// UpdateResponsePayloadSnapshot sets the "response_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateResponsePayloadSnapshot() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldResponsePayloadSnapshot)
	return u
}

// ClearResponsePayloadSnapshot clears the value of the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsert) ClearResponsePayloadSnapshot() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldResponsePayloadSnapshot)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *InvoiceApplicationUpsert) SetRetryCount(v int) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRetryCount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *InvoiceApplicationUpsert) AddRetryCount(v int) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldRetryCount, v)
	return u
}

// SetPdfFileData sets the "pdf_file_data" field.
func (u *InvoiceApplicationUpsert) SetPdfFileData(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldPdfFileData, v)
	return u
}

// UpdatePdfFileData sets the "pdf_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdatePdfFileData() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldPdfFileData)
	return u
}

// SetOfdFileData sets the "ofd_file_data" field.
func (u *InvoiceApplicationUpsert) SetOfdFileData(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldOfdFileData, v)
	return u
}

// UpdateOfdFileData sets the "ofd_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateOfdFileData() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldOfdFileData)
	return u
}

// SetXMLFileData sets the "xml_file_data" field.
func (u *InvoiceApplicationUpsert) SetXMLFileData(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldXMLFileData, v)
	return u
}

// UpdateXMLFileData sets the "xml_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateXMLFileData() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldXMLFileData)
	return u
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceApplicationUpsert) SetSubmittedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldSubmittedAt, v)
	return u
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateSubmittedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldSubmittedAt)
	return u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceApplicationUpsert) ClearSubmittedAt() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldSubmittedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsert) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUpdatedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertOne) UpdateNewValues() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplication.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationUpsertOne) Ignore() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertOne) DoNothing() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertOne) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertOne) SetUserID(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUserID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceApplicationUpsertOne) SetUserEmail(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUserEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserEmail()
	})
}

// SetBuyerType sets the "buyer_type" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerType(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerType(v)
	})
}

// UpdateBuyerType sets the "buyer_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerType() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerType()
	})
}

// SetBuyerName sets the "buyer_name" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerName(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerName(v)
	})
}

// UpdateBuyerName sets the "buyer_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerName() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerName()
	})
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerTaxNo(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerTaxNo(v)
	})
}

// UpdateBuyerTaxNo sets the "buyer_tax_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerTaxNo() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerTaxNo()
	})
}

// SetBuyerEmail sets the "buyer_email" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerEmail(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerEmail(v)
	})
}

// UpdateBuyerEmail sets the "buyer_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerEmail()
	})
}

// SetBuyerPhone sets the "buyer_phone" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerPhone(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerPhone(v)
	})
}

// UpdateBuyerPhone sets the "buyer_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerPhone() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerPhone()
	})
}

// SetBuyerAddress sets the "buyer_address" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerAddress(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerAddress(v)
	})
}

// UpdateBuyerAddress sets the "buyer_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerAddress() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerAddress()
	})
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerBankName(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerBankName(v)
	})
}

// UpdateBuyerBankName sets the "buyer_bank_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerBankName() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerBankName()
	})
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (u *InvoiceApplicationUpsertOne) SetBuyerBankAccount(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerBankAccount(v)
	})
}

// UpdateBuyerBankAccount sets the "buyer_bank_account" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateBuyerBankAccount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerBankAccount()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationUpsertOne) AddInvoiceAmount(v float64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceAmount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceType(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceType() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetContent sets the "content" field.
func (u *InvoiceApplicationUpsertOne) SetContent(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateContent() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateContent()
	})
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceApplicationUpsertOne) SetTaxRate(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxRate(v)
	})
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTaxRate() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxRate()
	})
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (u *InvoiceApplicationUpsertOne) SetTaxClassificationCode(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxClassificationCode(v)
	})
}

// UpdateTaxClassificationCode sets the "tax_classification_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTaxClassificationCode() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxClassificationCode()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertOne) SetStatus(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateStatus() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *InvoiceApplicationUpsertOne) SetProvider(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateProvider() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *InvoiceApplicationUpsertOne) SetProviderOrderID(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateProviderOrderID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProviderOrderID()
	})
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *InvoiceApplicationUpsertOne) SetProviderOrderNo(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProviderOrderNo(v)
	})
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateProviderOrderNo() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProviderOrderNo()
	})
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceCode(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceCode(v)
	})
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceCode() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceCode()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceApplicationUpsertOne) SetInvoiceNo(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateInvoiceNo() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceApplicationUpsertOne) SetIssuedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateIssuedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceApplicationUpsertOne) ClearIssuedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearIssuedAt()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *InvoiceApplicationUpsertOne) SetLastErrorCode(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateLastErrorCode() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *InvoiceApplicationUpsertOne) SetLastErrorMessage(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateLastErrorMessage() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsertOne) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRequestPayloadSnapshot(v)
	})
}

// UpdateRequestPayloadSnapshot sets the "request_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRequestPayloadSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRequestPayloadSnapshot()
	})
}

// ClearRequestPayloadSnapshot clears the value of the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsertOne) ClearRequestPayloadSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRequestPayloadSnapshot()
	})
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsertOne) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetResponsePayloadSnapshot(v)
	})
}

// UpdateResponsePayloadSnapshot sets the "response_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateResponsePayloadSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateResponsePayloadSnapshot()
	})
}

// ClearResponsePayloadSnapshot clears the value of the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsertOne) ClearResponsePayloadSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearResponsePayloadSnapshot()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *InvoiceApplicationUpsertOne) SetRetryCount(v int) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *InvoiceApplicationUpsertOne) AddRetryCount(v int) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRetryCount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRetryCount()
	})
}

// SetPdfFileData sets the "pdf_file_data" field.
func (u *InvoiceApplicationUpsertOne) SetPdfFileData(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetPdfFileData(v)
	})
}

// UpdatePdfFileData sets the "pdf_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdatePdfFileData() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdatePdfFileData()
	})
}

// SetOfdFileData sets the "ofd_file_data" field.
func (u *InvoiceApplicationUpsertOne) SetOfdFileData(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOfdFileData(v)
	})
}

// UpdateOfdFileData sets the "ofd_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateOfdFileData() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOfdFileData()
	})
}

// SetXMLFileData sets the "xml_file_data" field.
func (u *InvoiceApplicationUpsertOne) SetXMLFileData(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetXMLFileData(v)
	})
}

// UpdateXMLFileData sets the "xml_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateXMLFileData() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateXMLFileData()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceApplicationUpsertOne) SetSubmittedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateSubmittedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceApplicationUpsertOne) ClearSubmittedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUpdatedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationCreateBulk is the builder for creating many InvoiceApplication entities in bulk.
type InvoiceApplicationCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplication entities in the database.
func (_c *InvoiceApplicationCreateBulk) Save(ctx context.Context) ([]*InvoiceApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) SaveX(ctx context.Context) []*InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplication nodes.
type InvoiceApplicationUpsertBulk struct {
	create *InvoiceApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) UpdateNewValues() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplication.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) Ignore() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertBulk) DoNothing() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertBulk) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertBulk) SetUserID(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUserID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceApplicationUpsertBulk) SetUserEmail(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUserEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserEmail()
	})
}

// SetBuyerType sets the "buyer_type" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerType(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerType(v)
	})
}

// UpdateBuyerType sets the "buyer_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerType() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerType()
	})
}

// SetBuyerName sets the "buyer_name" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerName(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerName(v)
	})
}

// UpdateBuyerName sets the "buyer_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerName() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerName()
	})
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerTaxNo(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerTaxNo(v)
	})
}

// UpdateBuyerTaxNo sets the "buyer_tax_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerTaxNo() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerTaxNo()
	})
}

// SetBuyerEmail sets the "buyer_email" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerEmail(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerEmail(v)
	})
}

// UpdateBuyerEmail sets the "buyer_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerEmail()
	})
}

// SetBuyerPhone sets the "buyer_phone" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerPhone(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerPhone(v)
	})
}

// UpdateBuyerPhone sets the "buyer_phone" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerPhone() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerPhone()
	})
}

// SetBuyerAddress sets the "buyer_address" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerAddress(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerAddress(v)
	})
}

// UpdateBuyerAddress sets the "buyer_address" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerAddress() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerAddress()
	})
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerBankName(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerBankName(v)
	})
}

// UpdateBuyerBankName sets the "buyer_bank_name" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerBankName() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerBankName()
	})
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (u *InvoiceApplicationUpsertBulk) SetBuyerBankAccount(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetBuyerBankAccount(v)
	})
}

// UpdateBuyerBankAccount sets the "buyer_bank_account" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateBuyerBankAccount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateBuyerBankAccount()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationUpsertBulk) AddInvoiceAmount(v float64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceAmount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceType(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceType() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetContent sets the "content" field.
func (u *InvoiceApplicationUpsertBulk) SetContent(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateContent() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateContent()
	})
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceApplicationUpsertBulk) SetTaxRate(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxRate(v)
	})
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTaxRate() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxRate()
	})
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (u *InvoiceApplicationUpsertBulk) SetTaxClassificationCode(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxClassificationCode(v)
	})
}

// UpdateTaxClassificationCode sets the "tax_classification_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTaxClassificationCode() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxClassificationCode()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertBulk) SetStatus(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateStatus() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *InvoiceApplicationUpsertBulk) SetProvider(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateProvider() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderOrderID sets the "provider_order_id" field.
func (u *InvoiceApplicationUpsertBulk) SetProviderOrderID(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProviderOrderID(v)
	})
}

// UpdateProviderOrderID sets the "provider_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateProviderOrderID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProviderOrderID()
	})
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *InvoiceApplicationUpsertBulk) SetProviderOrderNo(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetProviderOrderNo(v)
	})
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateProviderOrderNo() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateProviderOrderNo()
	})
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceCode(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceCode(v)
	})
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceCode() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceCode()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceApplicationUpsertBulk) SetInvoiceNo(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateInvoiceNo() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceApplicationUpsertBulk) SetIssuedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateIssuedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearIssuedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearIssuedAt()
	})
}

// SetLastErrorCode sets the "last_error_code" field.
func (u *InvoiceApplicationUpsertBulk) SetLastErrorCode(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetLastErrorCode(v)
	})
}

// UpdateLastErrorCode sets the "last_error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateLastErrorCode() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateLastErrorCode()
	})
}

// SetLastErrorMessage sets the "last_error_message" field.
func (u *InvoiceApplicationUpsertBulk) SetLastErrorMessage(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetLastErrorMessage(v)
	})
}

// UpdateLastErrorMessage sets the "last_error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateLastErrorMessage() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateLastErrorMessage()
	})
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRequestPayloadSnapshot(v)
	})
}

// UpdateRequestPayloadSnapshot sets the "request_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRequestPayloadSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRequestPayloadSnapshot()
	})
}

// ClearRequestPayloadSnapshot clears the value of the "request_payload_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) ClearRequestPayloadSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRequestPayloadSnapshot()
	})
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetResponsePayloadSnapshot(v)
	})
}

// UpdateResponsePayloadSnapshot sets the "response_payload_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateResponsePayloadSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateResponsePayloadSnapshot()
	})
}

// ClearResponsePayloadSnapshot clears the value of the "response_payload_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) ClearResponsePayloadSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearResponsePayloadSnapshot()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *InvoiceApplicationUpsertBulk) SetRetryCount(v int) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *InvoiceApplicationUpsertBulk) AddRetryCount(v int) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRetryCount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRetryCount()
	})
}

// SetPdfFileData sets the "pdf_file_data" field.
func (u *InvoiceApplicationUpsertBulk) SetPdfFileData(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetPdfFileData(v)
	})
}

// UpdatePdfFileData sets the "pdf_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdatePdfFileData() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdatePdfFileData()
	})
}

// SetOfdFileData sets the "ofd_file_data" field.
func (u *InvoiceApplicationUpsertBulk) SetOfdFileData(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOfdFileData(v)
	})
}

// UpdateOfdFileData sets the "ofd_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateOfdFileData() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOfdFileData()
	})
}

// SetXMLFileData sets the "xml_file_data" field.
func (u *InvoiceApplicationUpsertBulk) SetXMLFileData(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetXMLFileData(v)
	})
}

// UpdateXMLFileData sets the "xml_file_data" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateXMLFileData() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateXMLFileData()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceApplicationUpsertBulk) SetSubmittedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateSubmittedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceApplicationUpsertBulk) ClearSubmittedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUpdatedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
