// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationDelete is the builder for deleting a InvoiceApplication entity.
type InvoiceApplicationDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// Where appends a list predicates to the InvoiceApplicationDelete builder.
func (_d *InvoiceApplicationDelete) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvoiceApplicationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvoiceApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoiceapplication.Table, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvoiceApplicationDeleteOne is the builder for deleting a single InvoiceApplication entity.
type InvoiceApplicationDeleteOne struct {
	_d *InvoiceApplicationDelete
}

// Where appends a list predicates to the InvoiceApplicationDelete builder.
func (_d *InvoiceApplicationDeleteOne) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvoiceApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
