// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationOrderCreate is the builder for creating a InvoiceApplicationOrder entity.
type InvoiceApplicationOrderCreate struct {
	config
	mutation *InvoiceApplicationOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (_c *InvoiceApplicationOrderCreate) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetInvoiceApplicationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceApplicationOrderCreate) SetUserID(v int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *InvoiceApplicationOrderCreate) SetPaymentOrderID(v int64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_c *InvoiceApplicationOrderCreate) SetOutTradeNo(v string) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOutTradeNo(v)
	return _c
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableOutTradeNo(v *string) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetOutTradeNo(*v)
	}
	return _c
}

// SetOrderType sets the "order_type" field.
func (_c *InvoiceApplicationOrderCreate) SetOrderType(v string) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOrderType(v)
	return _c
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableOrderType(v *string) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetOrderType(*v)
	}
	return _c
}

// SetOrderAmount sets the "order_amount" field.
func (_c *InvoiceApplicationOrderCreate) SetOrderAmount(v float64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetOrderAmount(v)
	return _c
}

// SetNillableOrderAmount sets the "order_amount" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableOrderAmount(v *float64) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetOrderAmount(*v)
	}
	return _c
}

// SetPayAmount sets the "pay_amount" field.
func (_c *InvoiceApplicationOrderCreate) SetPayAmount(v float64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetPayAmount(v)
	return _c
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillablePayAmount(v *float64) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetPayAmount(*v)
	}
	return _c
}

// SetRefundAmount sets the "refund_amount" field.
func (_c *InvoiceApplicationOrderCreate) SetRefundAmount(v float64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetRefundAmount(v)
	return _c
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableRefundAmount(v *float64) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetRefundAmount(*v)
	}
	return _c
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_c *InvoiceApplicationOrderCreate) SetInvoiceAmount(v float64) *InvoiceApplicationOrderCreate {
	_c.mutation.SetInvoiceAmount(v)
	return _c
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableInvoiceAmount(v *float64) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetInvoiceAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationOrderCreate) SetCreatedAt(v time.Time) *InvoiceApplicationOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationOrderCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInvoiceApplication sets the "invoice_application" edge to the InvoiceApplication entity.
func (_c *InvoiceApplicationOrderCreate) SetInvoiceApplication(v *InvoiceApplication) *InvoiceApplicationOrderCreate {
	return _c.SetInvoiceApplicationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceApplicationOrderCreate) SetUser(v *User) *InvoiceApplicationOrderCreate {
	return _c.SetUserID(v.ID)
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_c *InvoiceApplicationOrderCreate) SetPaymentOrder(v *PaymentOrder) *InvoiceApplicationOrderCreate {
	return _c.SetPaymentOrderID(v.ID)
}

// Mutation returns the InvoiceApplicationOrderMutation object of the builder.
func (_c *InvoiceApplicationOrderCreate) Mutation() *InvoiceApplicationOrderMutation {
	return _c.mutation
}

// Save creates the InvoiceApplicationOrder in the database.
func (_c *InvoiceApplicationOrderCreate) Save(ctx context.Context) (*InvoiceApplicationOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationOrderCreate) SaveX(ctx context.Context) *InvoiceApplicationOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationOrderCreate) defaults() {
	if _, ok := _c.mutation.OutTradeNo(); !ok {
		v := invoiceapplicationorder.DefaultOutTradeNo
		_c.mutation.SetOutTradeNo(v)
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		v := invoiceapplicationorder.DefaultOrderType
		_c.mutation.SetOrderType(v)
	}
	if _, ok := _c.mutation.OrderAmount(); !ok {
		v := invoiceapplicationorder.DefaultOrderAmount
		_c.mutation.SetOrderAmount(v)
	}
	if _, ok := _c.mutation.PayAmount(); !ok {
		v := invoiceapplicationorder.DefaultPayAmount
		_c.mutation.SetPayAmount(v)
	}
	if _, ok := _c.mutation.RefundAmount(); !ok {
		v := invoiceapplicationorder.DefaultRefundAmount
		_c.mutation.SetRefundAmount(v)
	}
	if _, ok := _c.mutation.InvoiceAmount(); !ok {
		v := invoiceapplicationorder.DefaultInvoiceAmount
		_c.mutation.SetInvoiceAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplicationorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationOrderCreate) check() error {
	if _, ok := _c.mutation.InvoiceApplicationID(); !ok {
		return &ValidationError{Name: "invoice_application_id", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.invoice_application_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.user_id"`)}
	}
	if _, ok := _c.mutation.PaymentOrderID(); !ok {
		return &ValidationError{Name: "payment_order_id", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.payment_order_id"`)}
	}
	if _, ok := _c.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.out_trade_no"`)}
	}
	if v, ok := _c.mutation.OutTradeNo(); ok {
		if err := invoiceapplicationorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.out_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		return &ValidationError{Name: "order_type", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.order_type"`)}
	}
	if v, ok := _c.mutation.OrderType(); ok {
		if err := invoiceapplicationorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.order_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderAmount(); !ok {
		return &ValidationError{Name: "order_amount", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.order_amount"`)}
	}
	if _, ok := _c.mutation.PayAmount(); !ok {
		return &ValidationError{Name: "pay_amount", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.pay_amount"`)}
	}
	if _, ok := _c.mutation.RefundAmount(); !ok {
		return &ValidationError{Name: "refund_amount", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.refund_amount"`)}
	}
	if _, ok := _c.mutation.InvoiceAmount(); !ok {
		return &ValidationError{Name: "invoice_amount", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.invoice_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplicationOrder.created_at"`)}
	}
	if len(_c.mutation.InvoiceApplicationIDs()) == 0 {
		return &ValidationError{Name: "invoice_application", err: errors.New(`ent: missing required edge "InvoiceApplicationOrder.invoice_application"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceApplicationOrder.user"`)}
	}
	if len(_c.mutation.PaymentOrderIDs()) == 0 {
		return &ValidationError{Name: "payment_order", err: errors.New(`ent: missing required edge "InvoiceApplicationOrder.payment_order"`)}
	}
	return nil
}

func (_c *InvoiceApplicationOrderCreate) sqlSave(ctx context.Context) (*InvoiceApplicationOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationOrderCreate) createSpec() (*InvoiceApplicationOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplicationOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplicationorder.Table, sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OutTradeNo(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := _c.mutation.OrderType(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderType, field.TypeString, value)
		_node.OrderType = value
	}
	if value, ok := _c.mutation.OrderAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderAmount, field.TypeFloat64, value)
		_node.OrderAmount = value
	}
	if value, ok := _c.mutation.PayAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldPayAmount, field.TypeFloat64, value)
		_node.PayAmount = value
	}
	if value, ok := _c.mutation.RefundAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldRefundAmount, field.TypeFloat64, value)
		_node.RefundAmount = value
	}
	if value, ok := _c.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldInvoiceAmount, field.TypeFloat64, value)
		_node.InvoiceAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplicationorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InvoiceApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.InvoiceApplicationTable,
			Columns: []string{invoiceapplicationorder.InvoiceApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoiceApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.UserTable,
			Columns: []string{invoiceapplicationorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PaymentOrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationOrder.Create().
//		SetInvoiceApplicationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationOrderUpsert) {
//			SetInvoiceApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationOrderUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreate) OnConflictColumns(columns ...string) *InvoiceApplicationOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationOrderUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationOrderUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplicationOrder node.
	InvoiceApplicationOrderUpsertOne struct {
		create *InvoiceApplicationOrderCreate
	}

	// InvoiceApplicationOrderUpsert is the "OnConflict" setter.
	InvoiceApplicationOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (u *InvoiceApplicationOrderUpsert) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldInvoiceApplicationID, v)
	return u
}

// UpdateInvoiceApplicationID sets the "invoice_application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateInvoiceApplicationID() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldInvoiceApplicationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationOrderUpsert) SetUserID(v int64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateUserID() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldUserID)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *InvoiceApplicationOrderUpsert) SetPaymentOrderID(v int64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdatePaymentOrderID() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldPaymentOrderID)
	return u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *InvoiceApplicationOrderUpsert) SetOutTradeNo(v string) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOutTradeNo, v)
	return u
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOutTradeNo() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOutTradeNo)
	return u
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsert) SetOrderType(v string) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOrderType, v)
	return u
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOrderType() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOrderType)
	return u
}

// SetOrderAmount sets the "order_amount" field.
func (u *InvoiceApplicationOrderUpsert) SetOrderAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldOrderAmount, v)
	return u
}

// UpdateOrderAmount sets the "order_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateOrderAmount() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldOrderAmount)
	return u
}

// AddOrderAmount adds v to the "order_amount" field.
func (u *InvoiceApplicationOrderUpsert) AddOrderAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Add(invoiceapplicationorder.FieldOrderAmount, v)
	return u
}

// SetPayAmount sets the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsert) SetPayAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldPayAmount, v)
	return u
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdatePayAmount() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldPayAmount)
	return u
}

// AddPayAmount adds v to the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsert) AddPayAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Add(invoiceapplicationorder.FieldPayAmount, v)
	return u
}

// SetRefundAmount sets the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsert) SetRefundAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldRefundAmount, v)
	return u
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateRefundAmount() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldRefundAmount)
	return u
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsert) AddRefundAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Add(invoiceapplicationorder.FieldRefundAmount, v)
	return u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsert) SetInvoiceAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Set(invoiceapplicationorder.FieldInvoiceAmount, v)
	return u
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsert) UpdateInvoiceAmount() *InvoiceApplicationOrderUpsert {
	u.SetExcluded(invoiceapplicationorder.FieldInvoiceAmount)
	return u
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsert) AddInvoiceAmount(v float64) *InvoiceApplicationOrderUpsert {
	u.Add(invoiceapplicationorder.FieldInvoiceAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertOne) UpdateNewValues() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplicationorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationOrderUpsertOne) Ignore() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationOrderUpsertOne) DoNothing() *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationOrderCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationOrderUpsertOne) Update(set func(*InvoiceApplicationOrderUpsert)) *InvoiceApplicationOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (u *InvoiceApplicationOrderUpsertOne) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetInvoiceApplicationID(v)
	})
}

// UpdateInvoiceApplicationID sets the "invoice_application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateInvoiceApplicationID() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateInvoiceApplicationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationOrderUpsertOne) SetUserID(v int64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateUserID() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *InvoiceApplicationOrderUpsertOne) SetPaymentOrderID(v int64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdatePaymentOrderID() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOutTradeNo(v string) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOutTradeNo(v)
	})
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOutTradeNo() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOutTradeNo()
	})
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOrderType(v string) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOrderType() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetOrderAmount sets the "order_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) SetOrderAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderAmount(v)
	})
}

// AddOrderAmount adds v to the "order_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) AddOrderAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddOrderAmount(v)
	})
}

// UpdateOrderAmount sets the "order_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateOrderAmount() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderAmount()
	})
}

// SetPayAmount sets the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) SetPayAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPayAmount(v)
	})
}

// AddPayAmount adds v to the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) AddPayAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddPayAmount(v)
	})
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdatePayAmount() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePayAmount()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) SetRefundAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) AddRefundAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateRefundAmount() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) SetInvoiceAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsertOne) AddInvoiceAmount(v float64) *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertOne) UpdateInvoiceAmount() *InvoiceApplicationOrderUpsertOne {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationOrderCreateBulk is the builder for creating many InvoiceApplicationOrder entities in bulk.
type InvoiceApplicationOrderCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplicationOrder entities in the database.
func (_c *InvoiceApplicationOrderCreateBulk) Save(ctx context.Context) ([]*InvoiceApplicationOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplicationOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreateBulk) SaveX(ctx context.Context) []*InvoiceApplicationOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplicationOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationOrderUpsert) {
//			SetInvoiceApplicationID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationOrderUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationOrderCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationOrderUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplicationOrder nodes.
type InvoiceApplicationOrderUpsertBulk struct {
	create *InvoiceApplicationOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertBulk) UpdateNewValues() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplicationorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplicationOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationOrderUpsertBulk) Ignore() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationOrderUpsertBulk) DoNothing() *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationOrderCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationOrderUpsertBulk) Update(set func(*InvoiceApplicationOrderUpsert)) *InvoiceApplicationOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetInvoiceApplicationID(v)
	})
}

// UpdateInvoiceApplicationID sets the "invoice_application_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateInvoiceApplicationID() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateInvoiceApplicationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetUserID(v int64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateUserID() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetPaymentOrderID(v int64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdatePaymentOrderID() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOutTradeNo(v string) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOutTradeNo(v)
	})
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOutTradeNo() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOutTradeNo()
	})
}

// SetOrderType sets the "order_type" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOrderType(v string) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOrderType() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetOrderAmount sets the "order_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetOrderAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetOrderAmount(v)
	})
}

// AddOrderAmount adds v to the "order_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) AddOrderAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddOrderAmount(v)
	})
}

// UpdateOrderAmount sets the "order_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateOrderAmount() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateOrderAmount()
	})
}

// SetPayAmount sets the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetPayAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetPayAmount(v)
	})
}

// AddPayAmount adds v to the "pay_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) AddPayAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddPayAmount(v)
	})
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdatePayAmount() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdatePayAmount()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetRefundAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) AddRefundAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateRefundAmount() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) SetInvoiceAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceApplicationOrderUpsertBulk) AddInvoiceAmount(v float64) *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceApplicationOrderUpsertBulk) UpdateInvoiceAmount() *InvoiceApplicationOrderUpsertBulk {
	return u.Update(func(s *InvoiceApplicationOrderUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
