// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationOrderUpdate is the builder for updating InvoiceApplicationOrder entities.
type InvoiceApplicationOrderUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationOrderMutation
}

// Where appends a list predicates to the InvoiceApplicationOrderUpdate builder.
func (_u *InvoiceApplicationOrderUpdate) Where(ps ...predicate.InvoiceApplicationOrder) *InvoiceApplicationOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (_u *InvoiceApplicationOrderUpdate) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderUpdate {
	_u.mutation.SetInvoiceApplicationID(v)
	return _u
}

// SetNillableInvoiceApplicationID sets the "invoice_application_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableInvoiceApplicationID(v *int64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetInvoiceApplicationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationOrderUpdate) SetUserID(v int64) *InvoiceApplicationOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableUserID(v *int64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *InvoiceApplicationOrderUpdate) SetPaymentOrderID(v int64) *InvoiceApplicationOrderUpdate {
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillablePaymentOrderID(v *int64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *InvoiceApplicationOrderUpdate) SetOutTradeNo(v string) *InvoiceApplicationOrderUpdate {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableOutTradeNo(v *string) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *InvoiceApplicationOrderUpdate) SetOrderType(v string) *InvoiceApplicationOrderUpdate {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableOrderType(v *string) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetOrderAmount sets the "order_amount" field.
func (_u *InvoiceApplicationOrderUpdate) SetOrderAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.ResetOrderAmount()
	_u.mutation.SetOrderAmount(v)
	return _u
}

// SetNillableOrderAmount sets the "order_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableOrderAmount(v *float64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetOrderAmount(*v)
	}
	return _u
}

// AddOrderAmount adds value to the "order_amount" field.
func (_u *InvoiceApplicationOrderUpdate) AddOrderAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.AddOrderAmount(v)
	return _u
}

// SetPayAmount sets the "pay_amount" field.
func (_u *InvoiceApplicationOrderUpdate) SetPayAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.ResetPayAmount()
	_u.mutation.SetPayAmount(v)
	return _u
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillablePayAmount(v *float64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetPayAmount(*v)
	}
	return _u
}

// AddPayAmount adds value to the "pay_amount" field.
func (_u *InvoiceApplicationOrderUpdate) AddPayAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.AddPayAmount(v)
	return _u
}

// SetRefundAmount sets the "refund_amount" field.
func (_u *InvoiceApplicationOrderUpdate) SetRefundAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.ResetRefundAmount()
	_u.mutation.SetRefundAmount(v)
	return _u
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableRefundAmount(v *float64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetRefundAmount(*v)
	}
	return _u
}

// AddRefundAmount adds value to the "refund_amount" field.
func (_u *InvoiceApplicationOrderUpdate) AddRefundAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.AddRefundAmount(v)
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceApplicationOrderUpdate) SetInvoiceAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdate) SetNillableInvoiceAmount(v *float64) *InvoiceApplicationOrderUpdate {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceApplicationOrderUpdate) AddInvoiceAmount(v float64) *InvoiceApplicationOrderUpdate {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// SetInvoiceApplication sets the "invoice_application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationOrderUpdate) SetInvoiceApplication(v *InvoiceApplication) *InvoiceApplicationOrderUpdate {
	return _u.SetInvoiceApplicationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationOrderUpdate) SetUser(v *User) *InvoiceApplicationOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *InvoiceApplicationOrderUpdate) SetPaymentOrder(v *PaymentOrder) *InvoiceApplicationOrderUpdate {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the InvoiceApplicationOrderMutation object of the builder.
func (_u *InvoiceApplicationOrderUpdate) Mutation() *InvoiceApplicationOrderMutation {
	return _u.mutation
}

// ClearInvoiceApplication clears the "invoice_application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationOrderUpdate) ClearInvoiceApplication() *InvoiceApplicationOrderUpdate {
	_u.mutation.ClearInvoiceApplication()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationOrderUpdate) ClearUser() *InvoiceApplicationOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *InvoiceApplicationOrderUpdate) ClearPaymentOrder() *InvoiceApplicationOrderUpdate {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationOrderUpdate) check() error {
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := invoiceapplicationorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := invoiceapplicationorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.order_type": %w`, err)}
		}
	}
	if _u.mutation.InvoiceApplicationCleared() && len(_u.mutation.InvoiceApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.invoice_application"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.user"`)
	}
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.payment_order"`)
	}
	return nil
}

func (_u *InvoiceApplicationOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplicationorder.Table, invoiceapplicationorder.Columns, sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldOrderAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldPayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPayAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldPayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.InvoiceApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.InvoiceApplicationTable,
			Columns: []string{invoiceapplicationorder.InvoiceApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.InvoiceApplicationTable,
			Columns: []string{invoiceapplicationorder.InvoiceApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.UserTable,
			Columns: []string{invoiceapplicationorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.UserTable,
			Columns: []string{invoiceapplicationorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplicationorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationOrderUpdateOne is the builder for updating a single InvoiceApplicationOrder entity.
type InvoiceApplicationOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationOrderMutation
}

// SetInvoiceApplicationID sets the "invoice_application_id" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetInvoiceApplicationID(v int64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.SetInvoiceApplicationID(v)
	return _u
}

// SetNillableInvoiceApplicationID sets the "invoice_application_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableInvoiceApplicationID(v *int64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetInvoiceApplicationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetUserID(v int64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableUserID(v *int64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetPaymentOrderID(v int64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillablePaymentOrderID(v *int64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetOutTradeNo(v string) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableOutTradeNo(v *string) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetOrderType(v string) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableOrderType(v *string) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetOrderAmount sets the "order_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetOrderAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ResetOrderAmount()
	_u.mutation.SetOrderAmount(v)
	return _u
}

// SetNillableOrderAmount sets the "order_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableOrderAmount(v *float64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetOrderAmount(*v)
	}
	return _u
}

// AddOrderAmount adds value to the "order_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) AddOrderAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.AddOrderAmount(v)
	return _u
}

// SetPayAmount sets the "pay_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetPayAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ResetPayAmount()
	_u.mutation.SetPayAmount(v)
	return _u
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillablePayAmount(v *float64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetPayAmount(*v)
	}
	return _u
}

// AddPayAmount adds value to the "pay_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) AddPayAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.AddPayAmount(v)
	return _u
}

// SetRefundAmount sets the "refund_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetRefundAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ResetRefundAmount()
	_u.mutation.SetRefundAmount(v)
	return _u
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableRefundAmount(v *float64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetRefundAmount(*v)
	}
	return _u
}

// AddRefundAmount adds value to the "refund_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) AddRefundAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.AddRefundAmount(v)
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) SetInvoiceAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceApplicationOrderUpdateOne) SetNillableInvoiceAmount(v *float64) *InvoiceApplicationOrderUpdateOne {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceApplicationOrderUpdateOne) AddInvoiceAmount(v float64) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// SetInvoiceApplication sets the "invoice_application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationOrderUpdateOne) SetInvoiceApplication(v *InvoiceApplication) *InvoiceApplicationOrderUpdateOne {
	return _u.SetInvoiceApplicationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationOrderUpdateOne) SetUser(v *User) *InvoiceApplicationOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_u *InvoiceApplicationOrderUpdateOne) SetPaymentOrder(v *PaymentOrder) *InvoiceApplicationOrderUpdateOne {
	return _u.SetPaymentOrderID(v.ID)
}

// Mutation returns the InvoiceApplicationOrderMutation object of the builder.
func (_u *InvoiceApplicationOrderUpdateOne) Mutation() *InvoiceApplicationOrderMutation {
	return _u.mutation
}

// ClearInvoiceApplication clears the "invoice_application" edge to the InvoiceApplication entity.
func (_u *InvoiceApplicationOrderUpdateOne) ClearInvoiceApplication() *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ClearInvoiceApplication()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationOrderUpdateOne) ClearUser() *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPaymentOrder clears the "payment_order" edge to the PaymentOrder entity.
func (_u *InvoiceApplicationOrderUpdateOne) ClearPaymentOrder() *InvoiceApplicationOrderUpdateOne {
	_u.mutation.ClearPaymentOrder()
	return _u
}

// Where appends a list predicates to the InvoiceApplicationOrderUpdate builder.
func (_u *InvoiceApplicationOrderUpdateOne) Where(ps ...predicate.InvoiceApplicationOrder) *InvoiceApplicationOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationOrderUpdateOne) Select(field string, fields ...string) *InvoiceApplicationOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationOrderUpdateOne) Save(ctx context.Context) (*InvoiceApplicationOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationOrderUpdateOne) SaveX(ctx context.Context) *InvoiceApplicationOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := invoiceapplicationorder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := invoiceapplicationorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplicationOrder.order_type": %w`, err)}
		}
	}
	if _u.mutation.InvoiceApplicationCleared() && len(_u.mutation.InvoiceApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.invoice_application"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.user"`)
	}
	if _u.mutation.PaymentOrderCleared() && len(_u.mutation.PaymentOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplicationOrder.payment_order"`)
	}
	return nil
}

func (_u *InvoiceApplicationOrderUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplicationOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplicationorder.Table, invoiceapplicationorder.Columns, sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplicationOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplicationorder.FieldID)
		for _, f := range fields {
			if !invoiceapplicationorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplicationorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldOrderAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldOrderAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldPayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPayAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldPayAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldRefundAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplicationorder.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoiceapplicationorder.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.InvoiceApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.InvoiceApplicationTable,
			Columns: []string{invoiceapplicationorder.InvoiceApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvoiceApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.InvoiceApplicationTable,
			Columns: []string{invoiceapplicationorder.InvoiceApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.UserTable,
			Columns: []string{invoiceapplicationorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.UserTable,
			Columns: []string{invoiceapplicationorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplicationorder.PaymentOrderTable,
			Columns: []string{invoiceapplicationorder.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceApplicationOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplicationorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
