// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationOrder is the model entity for the InvoiceApplicationOrder schema.
type InvoiceApplicationOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceApplicationID holds the value of the "invoice_application_id" field.
	InvoiceApplicationID int64 `json:"invoice_application_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID int64 `json:"payment_order_id,omitempty"`
	// OutTradeNo holds the value of the "out_trade_no" field.
	OutTradeNo string `json:"out_trade_no,omitempty"`
	// OrderType holds the value of the "order_type" field.
	OrderType string `json:"order_type,omitempty"`
	// OrderAmount holds the value of the "order_amount" field.
	OrderAmount float64 `json:"order_amount,omitempty"`
	// PayAmount holds the value of the "pay_amount" field.
	PayAmount float64 `json:"pay_amount,omitempty"`
	// RefundAmount holds the value of the "refund_amount" field.
	RefundAmount float64 `json:"refund_amount,omitempty"`
	// InvoiceAmount holds the value of the "invoice_amount" field.
	InvoiceAmount float64 `json:"invoice_amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceApplicationOrderQuery when eager-loading is set.
	Edges        InvoiceApplicationOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceApplicationOrderEdges holds the relations/edges for other nodes in the graph.
type InvoiceApplicationOrderEdges struct {
	// InvoiceApplication holds the value of the invoice_application edge.
	InvoiceApplication *InvoiceApplication `json:"invoice_application,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// PaymentOrder holds the value of the payment_order edge.
	PaymentOrder *PaymentOrder `json:"payment_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// InvoiceApplicationOrErr returns the InvoiceApplication value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationOrderEdges) InvoiceApplicationOrErr() (*InvoiceApplication, error) {
	if e.InvoiceApplication != nil {
		return e.InvoiceApplication, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invoiceapplication.Label}
	}
	return nil, &NotLoadedError{edge: "invoice_application"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PaymentOrderOrErr returns the PaymentOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationOrderEdges) PaymentOrderOrErr() (*PaymentOrder, error) {
	if e.PaymentOrder != nil {
		return e.PaymentOrder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "payment_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceApplicationOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceapplicationorder.FieldOrderAmount, invoiceapplicationorder.FieldPayAmount, invoiceapplicationorder.FieldRefundAmount, invoiceapplicationorder.FieldInvoiceAmount:
			values[i] = new(sql.NullFloat64)
		case invoiceapplicationorder.FieldID, invoiceapplicationorder.FieldInvoiceApplicationID, invoiceapplicationorder.FieldUserID, invoiceapplicationorder.FieldPaymentOrderID:
			values[i] = new(sql.NullInt64)
		case invoiceapplicationorder.FieldOutTradeNo, invoiceapplicationorder.FieldOrderType:
			values[i] = new(sql.NullString)
		case invoiceapplicationorder.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceApplicationOrder fields.
func (_m *InvoiceApplicationOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceapplicationorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceapplicationorder.FieldInvoiceApplicationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_application_id", values[i])
			} else if value.Valid {
				_m.InvoiceApplicationID = value.Int64
			}
		case invoiceapplicationorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoiceapplicationorder.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = value.Int64
			}
		case invoiceapplicationorder.FieldOutTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field out_trade_no", values[i])
			} else if value.Valid {
				_m.OutTradeNo = value.String
			}
		case invoiceapplicationorder.FieldOrderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value.Valid {
				_m.OrderType = value.String
			}
		case invoiceapplicationorder.FieldOrderAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field order_amount", values[i])
			} else if value.Valid {
				_m.OrderAmount = value.Float64
			}
		case invoiceapplicationorder.FieldPayAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_amount", values[i])
			} else if value.Valid {
				_m.PayAmount = value.Float64
			}
		case invoiceapplicationorder.FieldRefundAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value.Valid {
				_m.RefundAmount = value.Float64
			}
		case invoiceapplicationorder.FieldInvoiceAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_amount", values[i])
			} else if value.Valid {
				_m.InvoiceAmount = value.Float64
			}
		case invoiceapplicationorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceApplicationOrder.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceApplicationOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoiceApplication queries the "invoice_application" edge of the InvoiceApplicationOrder entity.
func (_m *InvoiceApplicationOrder) QueryInvoiceApplication() *InvoiceApplicationQuery {
	return NewInvoiceApplicationOrderClient(_m.config).QueryInvoiceApplication(_m)
}

// QueryUser queries the "user" edge of the InvoiceApplicationOrder entity.
func (_m *InvoiceApplicationOrder) QueryUser() *UserQuery {
	return NewInvoiceApplicationOrderClient(_m.config).QueryUser(_m)
}

// QueryPaymentOrder queries the "payment_order" edge of the InvoiceApplicationOrder entity.
func (_m *InvoiceApplicationOrder) QueryPaymentOrder() *PaymentOrderQuery {
	return NewInvoiceApplicationOrderClient(_m.config).QueryPaymentOrder(_m)
}

// Update returns a builder for updating this InvoiceApplicationOrder.
// Note that you need to call InvoiceApplicationOrder.Unwrap() before calling this method if this InvoiceApplicationOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceApplicationOrder) Update() *InvoiceApplicationOrderUpdateOne {
	return NewInvoiceApplicationOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceApplicationOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceApplicationOrder) Unwrap() *InvoiceApplicationOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceApplicationOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceApplicationOrder) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceApplicationOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_application_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceApplicationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("payment_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentOrderID))
	builder.WriteString(", ")
	builder.WriteString("out_trade_no=")
	builder.WriteString(_m.OutTradeNo)
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(_m.OrderType)
	builder.WriteString(", ")
	builder.WriteString("order_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderAmount))
	builder.WriteString(", ")
	builder.WriteString("pay_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayAmount))
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	builder.WriteString("invoice_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceAmount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceApplicationOrders is a parsable slice of InvoiceApplicationOrder.
type InvoiceApplicationOrders []*InvoiceApplicationOrder
