// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationOrderDelete is the builder for deleting a InvoiceApplicationOrder entity.
type InvoiceApplicationOrderDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationOrderMutation
}

// Where appends a list predicates to the InvoiceApplicationOrderDelete builder.
func (_d *InvoiceApplicationOrderDelete) Where(ps ...predicate.InvoiceApplicationOrder) *InvoiceApplicationOrderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvoiceApplicationOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationOrderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvoiceApplicationOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoiceapplicationorder.Table, sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvoiceApplicationOrderDeleteOne is the builder for deleting a single InvoiceApplicationOrder entity.
type InvoiceApplicationOrderDeleteOne struct {
	_d *InvoiceApplicationOrderDelete
}

// Where appends a list predicates to the InvoiceApplicationOrderDelete builder.
func (_d *InvoiceApplicationOrderDeleteOne) Where(ps ...predicate.InvoiceApplicationOrder) *InvoiceApplicationOrderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvoiceApplicationOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceapplicationorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceApplicationOrderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
