// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplicationorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplicationUpdate is the builder for updating InvoiceApplication entities.
type InvoiceApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdate) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdate) SetUserID(v int64) *InvoiceApplicationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableUserID(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceApplicationUpdate) SetUserEmail(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableUserEmail(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetBuyerType sets the "buyer_type" field.
func (_u *InvoiceApplicationUpdate) SetBuyerType(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerType(v)
	return _u
}

// SetNillableBuyerType sets the "buyer_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerType(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerType(*v)
	}
	return _u
}

// SetBuyerName sets the "buyer_name" field.
func (_u *InvoiceApplicationUpdate) SetBuyerName(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerName(v)
	return _u
}

// SetNillableBuyerName sets the "buyer_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerName(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerName(*v)
	}
	return _u
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (_u *InvoiceApplicationUpdate) SetBuyerTaxNo(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerTaxNo(v)
	return _u
}

// SetNillableBuyerTaxNo sets the "buyer_tax_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerTaxNo(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerTaxNo(*v)
	}
	return _u
}

// SetBuyerEmail sets the "buyer_email" field.
func (_u *InvoiceApplicationUpdate) SetBuyerEmail(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerEmail(v)
	return _u
}

// SetNillableBuyerEmail sets the "buyer_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerEmail(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerEmail(*v)
	}
	return _u
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_u *InvoiceApplicationUpdate) SetBuyerPhone(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerPhone(v)
	return _u
}

// SetNillableBuyerPhone sets the "buyer_phone" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerPhone(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerPhone(*v)
	}
	return _u
}

// SetBuyerAddress sets the "buyer_address" field.
func (_u *InvoiceApplicationUpdate) SetBuyerAddress(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerAddress(v)
	return _u
}

// SetNillableBuyerAddress sets the "buyer_address" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerAddress(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerAddress(*v)
	}
	return _u
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (_u *InvoiceApplicationUpdate) SetBuyerBankName(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerBankName(v)
	return _u
}

// SetNillableBuyerBankName sets the "buyer_bank_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerBankName(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerBankName(*v)
	}
	return _u
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (_u *InvoiceApplicationUpdate) SetBuyerBankAccount(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetBuyerBankAccount(v)
	return _u
}

// SetNillableBuyerBankAccount sets the "buyer_bank_account" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableBuyerBankAccount(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetBuyerBankAccount(*v)
	}
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceAmount(v *float64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceApplicationUpdate) AddInvoiceAmount(v float64) *InvoiceApplicationUpdate {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceType(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceType(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *InvoiceApplicationUpdate) SetContent(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableContent(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTaxRate sets the "tax_rate" field.
func (_u *InvoiceApplicationUpdate) SetTaxRate(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetTaxRate(v)
	return _u
}

// SetNillableTaxRate sets the "tax_rate" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTaxRate(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTaxRate(*v)
	}
	return _u
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (_u *InvoiceApplicationUpdate) SetTaxClassificationCode(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetTaxClassificationCode(v)
	return _u
}

// SetNillableTaxClassificationCode sets the "tax_classification_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTaxClassificationCode(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTaxClassificationCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdate) SetStatus(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableStatus(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceApplicationUpdate) SetProvider(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableProvider(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_u *InvoiceApplicationUpdate) SetProviderOrderID(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetProviderOrderID(v)
	return _u
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableProviderOrderID(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetProviderOrderID(*v)
	}
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *InvoiceApplicationUpdate) SetProviderOrderNo(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableProviderOrderNo(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// SetInvoiceCode sets the "invoice_code" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceCode(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoiceCode(v)
	return _u
}

// SetNillableInvoiceCode sets the "invoice_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceCode(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceCode(*v)
	}
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceApplicationUpdate) SetInvoiceNo(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableInvoiceNo(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceApplicationUpdate) SetIssuedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceApplicationUpdate) ClearIssuedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *InvoiceApplicationUpdate) SetLastErrorCode(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableLastErrorCode(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *InvoiceApplicationUpdate) SetLastErrorMessage(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableLastErrorMessage(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (_u *InvoiceApplicationUpdate) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpdate {
	_u.mutation.SetRequestPayloadSnapshot(v)
	return _u
}

// ClearRequestPayloadSnapshot clears the value of the "request_payload_snapshot" field.
func (_u *InvoiceApplicationUpdate) ClearRequestPayloadSnapshot() *InvoiceApplicationUpdate {
	_u.mutation.ClearRequestPayloadSnapshot()
	return _u
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (_u *InvoiceApplicationUpdate) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpdate {
	_u.mutation.SetResponsePayloadSnapshot(v)
	return _u
}

// ClearResponsePayloadSnapshot clears the value of the "response_payload_snapshot" field.
func (_u *InvoiceApplicationUpdate) ClearResponsePayloadSnapshot() *InvoiceApplicationUpdate {
	_u.mutation.ClearResponsePayloadSnapshot()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *InvoiceApplicationUpdate) SetRetryCount(v int) *InvoiceApplicationUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRetryCount(v *int) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *InvoiceApplicationUpdate) AddRetryCount(v int) *InvoiceApplicationUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetPdfFileData sets the "pdf_file_data" field.
func (_u *InvoiceApplicationUpdate) SetPdfFileData(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetPdfFileData(v)
	return _u
}

// SetNillablePdfFileData sets the "pdf_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillablePdfFileData(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetPdfFileData(*v)
	}
	return _u
}

// SetOfdFileData sets the "ofd_file_data" field.
func (_u *InvoiceApplicationUpdate) SetOfdFileData(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetOfdFileData(v)
	return _u
}

// SetNillableOfdFileData sets the "ofd_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableOfdFileData(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetOfdFileData(*v)
	}
	return _u
}

// SetXMLFileData sets the "xml_file_data" field.
func (_u *InvoiceApplicationUpdate) SetXMLFileData(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetXMLFileData(v)
	return _u
}

// SetNillableXMLFileData sets the "xml_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableXMLFileData(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetXMLFileData(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceApplicationUpdate) SetSubmittedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableSubmittedAt(v *time.Time) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *InvoiceApplicationUpdate) ClearSubmittedAt() *InvoiceApplicationUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdate) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) SetUser(v *User) *InvoiceApplicationUpdate {
	return _u.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_u *InvoiceApplicationUpdate) AddOrderIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdate) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdate) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdate) ClearUser() *InvoiceApplicationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrders clears all "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdate) ClearOrders() *InvoiceApplicationUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to InvoiceApplicationOrder entities by IDs.
func (_u *InvoiceApplicationUpdate) RemoveOrderIDs(ids ...int64) *InvoiceApplicationUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to InvoiceApplicationOrder entities.
func (_u *InvoiceApplicationUpdate) RemoveOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdate) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoiceapplication.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerType(); ok {
		if err := invoiceapplication.BuyerTypeValidator(v); err != nil {
			return &ValidationError{Name: "buyer_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerName(); ok {
		if err := invoiceapplication.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerTaxNo(); ok {
		if err := invoiceapplication.BuyerTaxNoValidator(v); err != nil {
			return &ValidationError{Name: "buyer_tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerEmail(); ok {
		if err := invoiceapplication.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerPhone(); ok {
		if err := invoiceapplication.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerBankName(); ok {
		if err := invoiceapplication.BuyerBankNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerBankAccount(); ok {
		if err := invoiceapplication.BuyerBankAccountValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := invoiceapplication.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxRate(); ok {
		if err := invoiceapplication.TaxRateValidator(v); err != nil {
			return &ValidationError{Name: "tax_rate", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxClassificationCode(); ok {
		if err := invoiceapplication.TaxClassificationCodeValidator(v); err != nil {
			return &ValidationError{Name: "tax_classification_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_classification_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoiceapplication.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderID(); ok {
		if err := invoiceapplication.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderNo(); ok {
		if err := invoiceapplication.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceCode(); ok {
		if err := invoiceapplication.InvoiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoiceapplication.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := invoiceapplication.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.last_error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoiceapplication.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerType(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerTaxNo(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerTaxNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerEmail(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerPhone(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerAddress(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerBankName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerBankAccount(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoiceapplication.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(invoiceapplication.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxRate(); ok {
		_spec.SetField(invoiceapplication.FieldTaxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxClassificationCode(); ok {
		_spec.SetField(invoiceapplication.FieldTaxClassificationCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoiceapplication.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderID(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceCode(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoiceapplication.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldRequestPayloadSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.RequestPayloadSnapshotCleared() {
		_spec.ClearField(invoiceapplication.FieldRequestPayloadSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponsePayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldResponsePayloadSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ResponsePayloadSnapshotCleared() {
		_spec.ClearField(invoiceapplication.FieldResponsePayloadSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(invoiceapplication.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(invoiceapplication.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PdfFileData(); ok {
		_spec.SetField(invoiceapplication.FieldPdfFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfdFileData(); ok {
		_spec.SetField(invoiceapplication.FieldOfdFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.XMLFileData(); ok {
		_spec.SetField(invoiceapplication.FieldXMLFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoiceapplication.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationUpdateOne is the builder for updating a single InvoiceApplication entity.
type InvoiceApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdateOne) SetUserID(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableUserID(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceApplicationUpdateOne) SetUserEmail(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableUserEmail(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetBuyerType sets the "buyer_type" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerType(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerType(v)
	return _u
}

// SetNillableBuyerType sets the "buyer_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerType(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerType(*v)
	}
	return _u
}

// SetBuyerName sets the "buyer_name" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerName(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerName(v)
	return _u
}

// SetNillableBuyerName sets the "buyer_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerName(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerName(*v)
	}
	return _u
}

// SetBuyerTaxNo sets the "buyer_tax_no" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerTaxNo(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerTaxNo(v)
	return _u
}

// SetNillableBuyerTaxNo sets the "buyer_tax_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerTaxNo(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerTaxNo(*v)
	}
	return _u
}

// SetBuyerEmail sets the "buyer_email" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerEmail(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerEmail(v)
	return _u
}

// SetNillableBuyerEmail sets the "buyer_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerEmail(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerEmail(*v)
	}
	return _u
}

// SetBuyerPhone sets the "buyer_phone" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerPhone(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerPhone(v)
	return _u
}

// SetNillableBuyerPhone sets the "buyer_phone" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerPhone(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerPhone(*v)
	}
	return _u
}

// SetBuyerAddress sets the "buyer_address" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerAddress(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerAddress(v)
	return _u
}

// SetNillableBuyerAddress sets the "buyer_address" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerAddress(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerAddress(*v)
	}
	return _u
}

// SetBuyerBankName sets the "buyer_bank_name" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerBankName(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerBankName(v)
	return _u
}

// SetNillableBuyerBankName sets the "buyer_bank_name" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerBankName(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerBankName(*v)
	}
	return _u
}

// SetBuyerBankAccount sets the "buyer_bank_account" field.
func (_u *InvoiceApplicationUpdateOne) SetBuyerBankAccount(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetBuyerBankAccount(v)
	return _u
}

// SetNillableBuyerBankAccount sets the "buyer_bank_account" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableBuyerBankAccount(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetBuyerBankAccount(*v)
	}
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceAmount(v *float64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceApplicationUpdateOne) AddInvoiceAmount(v float64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceType(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceType(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *InvoiceApplicationUpdateOne) SetContent(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableContent(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTaxRate sets the "tax_rate" field.
func (_u *InvoiceApplicationUpdateOne) SetTaxRate(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTaxRate(v)
	return _u
}

// SetNillableTaxRate sets the "tax_rate" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTaxRate(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTaxRate(*v)
	}
	return _u
}

// SetTaxClassificationCode sets the "tax_classification_code" field.
func (_u *InvoiceApplicationUpdateOne) SetTaxClassificationCode(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTaxClassificationCode(v)
	return _u
}

// SetNillableTaxClassificationCode sets the "tax_classification_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTaxClassificationCode(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTaxClassificationCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdateOne) SetStatus(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableStatus(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceApplicationUpdateOne) SetProvider(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableProvider(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderOrderID sets the "provider_order_id" field.
func (_u *InvoiceApplicationUpdateOne) SetProviderOrderID(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetProviderOrderID(v)
	return _u
}

// SetNillableProviderOrderID sets the "provider_order_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableProviderOrderID(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetProviderOrderID(*v)
	}
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *InvoiceApplicationUpdateOne) SetProviderOrderNo(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableProviderOrderNo(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// SetInvoiceCode sets the "invoice_code" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceCode(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoiceCode(v)
	return _u
}

// SetNillableInvoiceCode sets the "invoice_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceCode(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceCode(*v)
	}
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceApplicationUpdateOne) SetInvoiceNo(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableInvoiceNo(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceApplicationUpdateOne) SetIssuedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearIssuedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *InvoiceApplicationUpdateOne) SetLastErrorCode(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableLastErrorCode(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *InvoiceApplicationUpdateOne) SetLastErrorMessage(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableLastErrorMessage(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// SetRequestPayloadSnapshot sets the "request_payload_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) SetRequestPayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRequestPayloadSnapshot(v)
	return _u
}

// ClearRequestPayloadSnapshot clears the value of the "request_payload_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) ClearRequestPayloadSnapshot() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRequestPayloadSnapshot()
	return _u
}

// SetResponsePayloadSnapshot sets the "response_payload_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) SetResponsePayloadSnapshot(v map[string]interface{}) *InvoiceApplicationUpdateOne {
	_u.mutation.SetResponsePayloadSnapshot(v)
	return _u
}

// ClearResponsePayloadSnapshot clears the value of the "response_payload_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) ClearResponsePayloadSnapshot() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearResponsePayloadSnapshot()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *InvoiceApplicationUpdateOne) SetRetryCount(v int) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRetryCount(v *int) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *InvoiceApplicationUpdateOne) AddRetryCount(v int) *InvoiceApplicationUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetPdfFileData sets the "pdf_file_data" field.
func (_u *InvoiceApplicationUpdateOne) SetPdfFileData(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetPdfFileData(v)
	return _u
}

// SetNillablePdfFileData sets the "pdf_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillablePdfFileData(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetPdfFileData(*v)
	}
	return _u
}

// SetOfdFileData sets the "ofd_file_data" field.
func (_u *InvoiceApplicationUpdateOne) SetOfdFileData(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetOfdFileData(v)
	return _u
}

// SetNillableOfdFileData sets the "ofd_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableOfdFileData(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetOfdFileData(*v)
	}
	return _u
}

// SetXMLFileData sets the "xml_file_data" field.
func (_u *InvoiceApplicationUpdateOne) SetXMLFileData(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetXMLFileData(v)
	return _u
}

// SetNillableXMLFileData sets the "xml_file_data" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableXMLFileData(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetXMLFileData(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceApplicationUpdateOne) SetSubmittedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableSubmittedAt(v *time.Time) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *InvoiceApplicationUpdateOne) ClearSubmittedAt() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdateOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) SetUser(v *User) *InvoiceApplicationUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the InvoiceApplicationOrder entity by IDs.
func (_u *InvoiceApplicationUpdateOne) AddOrderIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdateOne) AddOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdateOne) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceApplicationUpdateOne) ClearUser() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrders clears all "orders" edges to the InvoiceApplicationOrder entity.
func (_u *InvoiceApplicationUpdateOne) ClearOrders() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to InvoiceApplicationOrder entities by IDs.
func (_u *InvoiceApplicationUpdateOne) RemoveOrderIDs(ids ...int64) *InvoiceApplicationUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to InvoiceApplicationOrder entities.
func (_u *InvoiceApplicationUpdateOne) RemoveOrders(v ...*InvoiceApplicationOrder) *InvoiceApplicationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdateOne) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationUpdateOne) Select(field string, fields ...string) *InvoiceApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplication entity.
func (_u *InvoiceApplicationUpdateOne) Save(ctx context.Context) (*InvoiceApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) SaveX(ctx context.Context) *InvoiceApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoiceapplication.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerType(); ok {
		if err := invoiceapplication.BuyerTypeValidator(v); err != nil {
			return &ValidationError{Name: "buyer_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerName(); ok {
		if err := invoiceapplication.BuyerNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerTaxNo(); ok {
		if err := invoiceapplication.BuyerTaxNoValidator(v); err != nil {
			return &ValidationError{Name: "buyer_tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerEmail(); ok {
		if err := invoiceapplication.BuyerEmailValidator(v); err != nil {
			return &ValidationError{Name: "buyer_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerPhone(); ok {
		if err := invoiceapplication.BuyerPhoneValidator(v); err != nil {
			return &ValidationError{Name: "buyer_phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerBankName(); ok {
		if err := invoiceapplication.BuyerBankNameValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerBankAccount(); ok {
		if err := invoiceapplication.BuyerBankAccountValidator(v); err != nil {
			return &ValidationError{Name: "buyer_bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.buyer_bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceapplication.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := invoiceapplication.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxRate(); ok {
		if err := invoiceapplication.TaxRateValidator(v); err != nil {
			return &ValidationError{Name: "tax_rate", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxClassificationCode(); ok {
		if err := invoiceapplication.TaxClassificationCodeValidator(v); err != nil {
			return &ValidationError{Name: "tax_classification_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.tax_classification_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoiceapplication.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderID(); ok {
		if err := invoiceapplication.ProviderOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderNo(); ok {
		if err := invoiceapplication.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.provider_order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceCode(); ok {
		if err := invoiceapplication.InvoiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoiceapplication.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := invoiceapplication.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.last_error_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceApplication.user"`)
	}
	return nil
}

func (_u *InvoiceApplicationUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplication.FieldID)
		for _, f := range fields {
			if !invoiceapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoiceapplication.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerType(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerTaxNo(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerTaxNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerEmail(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerPhone(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerAddress(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerBankName(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerBankAccount(); ok {
		_spec.SetField(invoiceapplication.FieldBuyerBankAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoiceapplication.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(invoiceapplication.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxRate(); ok {
		_spec.SetField(invoiceapplication.FieldTaxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxClassificationCode(); ok {
		_spec.SetField(invoiceapplication.FieldTaxClassificationCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoiceapplication.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderID(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(invoiceapplication.FieldProviderOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceCode(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoiceapplication.FieldInvoiceNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoiceapplication.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldLastErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldRequestPayloadSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.RequestPayloadSnapshotCleared() {
		_spec.ClearField(invoiceapplication.FieldRequestPayloadSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponsePayloadSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldResponsePayloadSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ResponsePayloadSnapshotCleared() {
		_spec.ClearField(invoiceapplication.FieldResponsePayloadSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(invoiceapplication.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(invoiceapplication.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PdfFileData(); ok {
		_spec.SetField(invoiceapplication.FieldPdfFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.OfdFileData(); ok {
		_spec.SetField(invoiceapplication.FieldOfdFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.XMLFileData(); ok {
		_spec.SetField(invoiceapplication.FieldXMLFileData, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoiceapplication.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(invoiceapplication.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceapplication.UserTable,
			Columns: []string{invoiceapplication.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoiceapplication.OrdersTable,
			Columns: []string{invoiceapplication.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceapplicationorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
