// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceApplication is the model entity for the InvoiceApplication schema.
type InvoiceApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail string `json:"user_email,omitempty"`
	// BuyerType holds the value of the "buyer_type" field.
	BuyerType string `json:"buyer_type,omitempty"`
	// BuyerName holds the value of the "buyer_name" field.
	BuyerName string `json:"buyer_name,omitempty"`
	// BuyerTaxNo holds the value of the "buyer_tax_no" field.
	BuyerTaxNo string `json:"buyer_tax_no,omitempty"`
	// BuyerEmail holds the value of the "buyer_email" field.
	BuyerEmail string `json:"buyer_email,omitempty"`
	// BuyerPhone holds the value of the "buyer_phone" field.
	BuyerPhone string `json:"buyer_phone,omitempty"`
	// BuyerAddress holds the value of the "buyer_address" field.
	BuyerAddress string `json:"buyer_address,omitempty"`
	// BuyerBankName holds the value of the "buyer_bank_name" field.
	BuyerBankName string `json:"buyer_bank_name,omitempty"`
	// BuyerBankAccount holds the value of the "buyer_bank_account" field.
	BuyerBankAccount string `json:"buyer_bank_account,omitempty"`
	// InvoiceAmount holds the value of the "invoice_amount" field.
	InvoiceAmount float64 `json:"invoice_amount,omitempty"`
	// InvoiceType holds the value of the "invoice_type" field.
	InvoiceType string `json:"invoice_type,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// TaxRate holds the value of the "tax_rate" field.
	TaxRate string `json:"tax_rate,omitempty"`
	// TaxClassificationCode holds the value of the "tax_classification_code" field.
	TaxClassificationCode string `json:"tax_classification_code,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderOrderID holds the value of the "provider_order_id" field.
	ProviderOrderID string `json:"provider_order_id,omitempty"`
	// ProviderOrderNo holds the value of the "provider_order_no" field.
	ProviderOrderNo string `json:"provider_order_no,omitempty"`
	// InvoiceCode holds the value of the "invoice_code" field.
	InvoiceCode string `json:"invoice_code,omitempty"`
	// InvoiceNo holds the value of the "invoice_no" field.
	InvoiceNo string `json:"invoice_no,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage string `json:"last_error_message,omitempty"`
	// RequestPayloadSnapshot holds the value of the "request_payload_snapshot" field.
	RequestPayloadSnapshot map[string]interface{} `json:"request_payload_snapshot,omitempty"`
	// ResponsePayloadSnapshot holds the value of the "response_payload_snapshot" field.
	ResponsePayloadSnapshot map[string]interface{} `json:"response_payload_snapshot,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// PdfFileData holds the value of the "pdf_file_data" field.
	PdfFileData string `json:"pdf_file_data,omitempty"`
	// OfdFileData holds the value of the "ofd_file_data" field.
	OfdFileData string `json:"ofd_file_data,omitempty"`
	// XMLFileData holds the value of the "xml_file_data" field.
	XMLFileData string `json:"xml_file_data,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceApplicationQuery when eager-loading is set.
	Edges        InvoiceApplicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceApplicationEdges holds the relations/edges for other nodes in the graph.
type InvoiceApplicationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*InvoiceApplicationOrder `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceApplicationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e InvoiceApplicationEdges) OrdersOrErr() ([]*InvoiceApplicationOrder, error) {
	if e.loadedTypes[1] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldRequestPayloadSnapshot, invoiceapplication.FieldResponsePayloadSnapshot:
			values[i] = new([]byte)
		case invoiceapplication.FieldInvoiceAmount:
			values[i] = new(sql.NullFloat64)
		case invoiceapplication.FieldID, invoiceapplication.FieldUserID, invoiceapplication.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case invoiceapplication.FieldUserEmail, invoiceapplication.FieldBuyerType, invoiceapplication.FieldBuyerName, invoiceapplication.FieldBuyerTaxNo, invoiceapplication.FieldBuyerEmail, invoiceapplication.FieldBuyerPhone, invoiceapplication.FieldBuyerAddress, invoiceapplication.FieldBuyerBankName, invoiceapplication.FieldBuyerBankAccount, invoiceapplication.FieldInvoiceType, invoiceapplication.FieldContent, invoiceapplication.FieldTaxRate, invoiceapplication.FieldTaxClassificationCode, invoiceapplication.FieldStatus, invoiceapplication.FieldProvider, invoiceapplication.FieldProviderOrderID, invoiceapplication.FieldProviderOrderNo, invoiceapplication.FieldInvoiceCode, invoiceapplication.FieldInvoiceNo, invoiceapplication.FieldLastErrorCode, invoiceapplication.FieldLastErrorMessage, invoiceapplication.FieldPdfFileData, invoiceapplication.FieldOfdFileData, invoiceapplication.FieldXMLFileData:
			values[i] = new(sql.NullString)
		case invoiceapplication.FieldIssuedAt, invoiceapplication.FieldSubmittedAt, invoiceapplication.FieldCreatedAt, invoiceapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceApplication fields.
func (_m *InvoiceApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoiceapplication.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case invoiceapplication.FieldBuyerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_type", values[i])
			} else if value.Valid {
				_m.BuyerType = value.String
			}
		case invoiceapplication.FieldBuyerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_name", values[i])
			} else if value.Valid {
				_m.BuyerName = value.String
			}
		case invoiceapplication.FieldBuyerTaxNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_tax_no", values[i])
			} else if value.Valid {
				_m.BuyerTaxNo = value.String
			}
		case invoiceapplication.FieldBuyerEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_email", values[i])
			} else if value.Valid {
				_m.BuyerEmail = value.String
			}
		case invoiceapplication.FieldBuyerPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_phone", values[i])
			} else if value.Valid {
				_m.BuyerPhone = value.String
			}
		case invoiceapplication.FieldBuyerAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_address", values[i])
			} else if value.Valid {
				_m.BuyerAddress = value.String
			}
		case invoiceapplication.FieldBuyerBankName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_bank_name", values[i])
			} else if value.Valid {
				_m.BuyerBankName = value.String
			}
		case invoiceapplication.FieldBuyerBankAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_bank_account", values[i])
			} else if value.Valid {
				_m.BuyerBankAccount = value.String
			}
		case invoiceapplication.FieldInvoiceAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_amount", values[i])
			} else if value.Valid {
				_m.InvoiceAmount = value.Float64
			}
		case invoiceapplication.FieldInvoiceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_type", values[i])
			} else if value.Valid {
				_m.InvoiceType = value.String
			}
		case invoiceapplication.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case invoiceapplication.FieldTaxRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_rate", values[i])
			} else if value.Valid {
				_m.TaxRate = value.String
			}
		case invoiceapplication.FieldTaxClassificationCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_classification_code", values[i])
			} else if value.Valid {
				_m.TaxClassificationCode = value.String
			}
		case invoiceapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoiceapplication.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case invoiceapplication.FieldProviderOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_order_id", values[i])
			} else if value.Valid {
				_m.ProviderOrderID = value.String
			}
		case invoiceapplication.FieldProviderOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_order_no", values[i])
			} else if value.Valid {
				_m.ProviderOrderNo = value.String
			}
		case invoiceapplication.FieldInvoiceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_code", values[i])
			} else if value.Valid {
				_m.InvoiceCode = value.String
			}
		case invoiceapplication.FieldInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_no", values[i])
			} else if value.Valid {
				_m.InvoiceNo = value.String
			}
		case invoiceapplication.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case invoiceapplication.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = value.String
			}
		case invoiceapplication.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = value.String
			}
		case invoiceapplication.FieldRequestPayloadSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestPayloadSnapshot); err != nil {
					return fmt.Errorf("unmarshal field request_payload_snapshot: %w", err)
				}
			}
		case invoiceapplication.FieldResponsePayloadSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_payload_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponsePayloadSnapshot); err != nil {
					return fmt.Errorf("unmarshal field response_payload_snapshot: %w", err)
				}
			}
		case invoiceapplication.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case invoiceapplication.FieldPdfFileData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_file_data", values[i])
			} else if value.Valid {
				_m.PdfFileData = value.String
			}
		case invoiceapplication.FieldOfdFileData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ofd_file_data", values[i])
			} else if value.Valid {
				_m.OfdFileData = value.String
			}
		case invoiceapplication.FieldXMLFileData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field xml_file_data", values[i])
			} else if value.Valid {
				_m.XMLFileData = value.String
			}
		case invoiceapplication.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case invoiceapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoiceapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceApplication.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryUser() *UserQuery {
	return NewInvoiceApplicationClient(_m.config).QueryUser(_m)
}

// QueryOrders queries the "orders" edge of the InvoiceApplication entity.
func (_m *InvoiceApplication) QueryOrders() *InvoiceApplicationOrderQuery {
	return NewInvoiceApplicationClient(_m.config).QueryOrders(_m)
}

// Update returns a builder for updating this InvoiceApplication.
// Note that you need to call InvoiceApplication.Unwrap() before calling this method if this InvoiceApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceApplication) Update() *InvoiceApplicationUpdateOne {
	return NewInvoiceApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceApplication) Unwrap() *InvoiceApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceApplication) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("buyer_type=")
	builder.WriteString(_m.BuyerType)
	builder.WriteString(", ")
	builder.WriteString("buyer_name=")
	builder.WriteString(_m.BuyerName)
	builder.WriteString(", ")
	builder.WriteString("buyer_tax_no=")
	builder.WriteString(_m.BuyerTaxNo)
	builder.WriteString(", ")
	builder.WriteString("buyer_email=")
	builder.WriteString(_m.BuyerEmail)
	builder.WriteString(", ")
	builder.WriteString("buyer_phone=")
	builder.WriteString(_m.BuyerPhone)
	builder.WriteString(", ")
	builder.WriteString("buyer_address=")
	builder.WriteString(_m.BuyerAddress)
	builder.WriteString(", ")
	builder.WriteString("buyer_bank_name=")
	builder.WriteString(_m.BuyerBankName)
	builder.WriteString(", ")
	builder.WriteString("buyer_bank_account=")
	builder.WriteString(_m.BuyerBankAccount)
	builder.WriteString(", ")
	builder.WriteString("invoice_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceAmount))
	builder.WriteString(", ")
	builder.WriteString("invoice_type=")
	builder.WriteString(_m.InvoiceType)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("tax_rate=")
	builder.WriteString(_m.TaxRate)
	builder.WriteString(", ")
	builder.WriteString("tax_classification_code=")
	builder.WriteString(_m.TaxClassificationCode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_order_id=")
	builder.WriteString(_m.ProviderOrderID)
	builder.WriteString(", ")
	builder.WriteString("provider_order_no=")
	builder.WriteString(_m.ProviderOrderNo)
	builder.WriteString(", ")
	builder.WriteString("invoice_code=")
	builder.WriteString(_m.InvoiceCode)
	builder.WriteString(", ")
	builder.WriteString("invoice_no=")
	builder.WriteString(_m.InvoiceNo)
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error_code=")
	builder.WriteString(_m.LastErrorCode)
	builder.WriteString(", ")
	builder.WriteString("last_error_message=")
	builder.WriteString(_m.LastErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("request_payload_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPayloadSnapshot))
	builder.WriteString(", ")
	builder.WriteString("response_payload_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponsePayloadSnapshot))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("pdf_file_data=")
	builder.WriteString(_m.PdfFileData)
	builder.WriteString(", ")
	builder.WriteString("ofd_file_data=")
	builder.WriteString(_m.OfdFileData)
	builder.WriteString(", ")
	builder.WriteString("xml_file_data=")
	builder.WriteString(_m.XMLFileData)
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceApplications is a parsable slice of InvoiceApplication.
type InvoiceApplications []*InvoiceApplication
