package service

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// GatewayRetryBillingLedger is an optional, shared ledger used to correlate a
// client retry with a gateway attempt that failed before any semantic output.
// The narrow interface keeps test-only GatewayCache implementations compatible;
// production's Redis-backed gateway cache implements it.
type GatewayRetryBillingLedger interface {
	MarkPreSemanticFailure(ctx context.Context, fingerprint, logicalRequestID string, ttl time.Duration) error
	GetPreSemanticFailure(ctx context.Context, fingerprint string) (logicalRequestID string, ok bool, err error)
	ClearPreSemanticFailure(ctx context.Context, fingerprint string) error
}

// gatewayRetryMarkerTTL intentionally remains bounded. A retry marker is only
// valid for an automatic retry of the same request, not for a later deliberate
// submission of the same prompt.
const gatewayRetryMarkerTTL = 10 * time.Minute
const gatewayRetryLogicalRequestPrefix = "gateway-retry:v1:"
const gatewayRetryBillingFingerprintPrefix = "sub2api-gateway-retry-billing:v1|"

// GatewayRetryMarkerTTL exposes the bounded retry window to handlers and tests
// without making it an operational environment variable.
func GatewayRetryMarkerTTL() time.Duration {
	return gatewayRetryMarkerTTL
}

// IsGatewayRetryLogicalRequestID identifies the bounded logical request IDs
// generated by BuildGatewayRetryFingerprint. It is intentionally strict so a
// normal client request ID can never suppress its usage log accidentally.
func IsGatewayRetryLogicalRequestID(requestID string) bool {
	return strings.HasPrefix(strings.TrimSpace(requestID), gatewayRetryLogicalRequestPrefix)
}

// BuildGatewayRetryBillingFingerprint returns the account-independent billing
// fingerprint for a linked retry. A failover can settle the same logical
// request on Kiro, Claude, or another account, so the physical account and
// observed token split must not turn the second claim into a conflict.
func BuildGatewayRetryBillingFingerprint(logicalRequestID string) string {
	logicalRequestID = strings.TrimSpace(logicalRequestID)
	if !IsGatewayRetryLogicalRequestID(logicalRequestID) {
		return ""
	}
	digest := sha256.Sum256([]byte(gatewayRetryBillingFingerprintPrefix + logicalRequestID))
	return hex.EncodeToString(digest[:])
}

// BuildGatewayRetryFingerprint derives a stable, tenant-scoped fingerprint for
// the exact inbound request. It deliberately excludes the generated client
// request ID because SDK retries receive a fresh ID from middleware. The body
// hash is included so an intentionally different turn can never consume an old
// failed-attempt marker.
func BuildGatewayRetryFingerprint(
	userID, apiKeyID int64,
	groupID *int64,
	platform, model, sessionID string,
	body []byte,
) (fingerprint, logicalRequestID string) {
	if len(body) == 0 || userID <= 0 || apiKeyID <= 0 {
		return "", ""
	}
	gid := int64(0)
	if groupID != nil {
		gid = *groupID
	}
	bodyHash := HashUsageRequestPayload(body)
	raw := fmt.Sprintf(
		"sub2api-gateway-retry-v1|user=%d|api_key=%d|group=%d|platform=%s|model=%s|session=%s|body=%s",
		userID,
		apiKeyID,
		gid,
		strings.TrimSpace(platform),
		strings.TrimSpace(model),
		strings.TrimSpace(sessionID),
		bodyHash,
	)
	digest := sha256.Sum256([]byte(raw))
	fingerprint = hex.EncodeToString(digest[:])
	logicalRequestID = gatewayRetryLogicalRequestPrefix + fingerprint
	return fingerprint, logicalRequestID
}

// IsGatewayPreSemanticRetryableFailure limits retry billing shielding to
// failures that the gateway itself classifies as safe to retry before semantic
// output. Client-visible invalid requests and post-semantic truncation must not
// silently inherit a previous billing identity.
func IsGatewayPreSemanticRetryableFailure(failoverErr *UpstreamFailoverError) bool {
	if failoverErr == nil || failoverErr.FailoverProhibited {
		return false
	}
	switch failoverErr.FailureKind {
	case UpstreamFailureRateLimited,
		UpstreamFailureResponseHeaderTimeout,
		UpstreamFailureFirstSemanticTimeout,
		UpstreamFailureTransportError,
		UpstreamFailureIncompleteStream:
		return true
	}
	if failoverErr.RetryableOnSameAccount || failoverErr.RequestScopedTransient || failoverErr.KiroRateLimited || failoverErr.AnthropicSoftRateLimit {
		return true
	}
	return failoverErr.StatusCode == http.StatusTooManyRequests || failoverErr.StatusCode >= http.StatusInternalServerError
}

// IsGatewayPreSemanticNetworkError exposes the provider transport classifier
// to the handler for passthrough paths that return a plain error instead of an
// UpstreamFailoverError. It is deliberately limited to failures before any
// response bytes were available.
func IsGatewayPreSemanticNetworkError(err error) bool {
	return isRetryablePreResponseNetworkError(err)
}

func (s *GatewayService) MarkGatewayPreSemanticFailure(ctx context.Context, fingerprint, logicalRequestID string) error {
	if s == nil || s.cache == nil || strings.TrimSpace(fingerprint) == "" {
		return nil
	}
	ledger, ok := s.cache.(GatewayRetryBillingLedger)
	if !ok {
		return nil
	}
	return ledger.MarkPreSemanticFailure(ctx, strings.TrimSpace(fingerprint), strings.TrimSpace(logicalRequestID), gatewayRetryMarkerTTL)
}

func (s *GatewayService) GetGatewayPreSemanticRetry(ctx context.Context, fingerprint string) (string, bool, error) {
	if s == nil || s.cache == nil || strings.TrimSpace(fingerprint) == "" {
		return "", false, nil
	}
	ledger, ok := s.cache.(GatewayRetryBillingLedger)
	if !ok {
		return "", false, nil
	}
	return ledger.GetPreSemanticFailure(ctx, strings.TrimSpace(fingerprint))
}

func (s *GatewayService) ClearGatewayPreSemanticRetry(ctx context.Context, fingerprint string) error {
	if s == nil || s.cache == nil || strings.TrimSpace(fingerprint) == "" {
		return nil
	}
	ledger, ok := s.cache.(GatewayRetryBillingLedger)
	if !ok {
		return nil
	}
	return ledger.ClearPreSemanticFailure(ctx, strings.TrimSpace(fingerprint))
}
