package service

import (
	"archive/zip"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func officeArchive(t *testing.T, extra map[string]string) []byte {
	t.Helper()
	var out bytes.Buffer
	z := zip.NewWriter(&out)
	parts := map[string]string{"[Content_Types].xml": "<Types/>", "word/document.xml": "<document/>"}
	for k, v := range extra {
		parts[k] = v
	}
	for k, v := range parts {
		w, err := z.Create(k)
		require.NoError(t, err)
		_, err = io.WriteString(w, v)
		require.NoError(t, err)
	}
	require.NoError(t, z.Close())
	return out.Bytes()
}
func TestWebAgentOfficeClientValidatesIntegrity(t *testing.T) {
	content := officeArchive(t, nil)
	token := strings.Repeat("x", 32)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "Bearer "+token, r.Header.Get("Authorization"))
		require.Equal(t, "/render", r.URL.Path)
		json.NewEncoder(w).Encode(map[string]any{"protocol_version": 1, "extension": "docx", "mime": webAgentArtifactTypes["document"].mime,
			"file_base64": content, "file_sha256": fmt.Sprintf("%x", sha256.Sum256(content)), "size_bytes": len(content), "preview_pdf_base64": []byte("%PDF-1.7\n")})
	}))
	defer server.Close()
	client, err := NewWebAgentOfficeClient(server.URL, token)
	require.NoError(t, err)
	result, err := client.Render(context.Background(), "document", json.RawMessage(`{"kind":"document","title":"test","sections":[]}`))
	require.NoError(t, err)
	require.Equal(t, content, result.File)
	_, err = client.Render(context.Background(), "slides", json.RawMessage(`{"kind":"document"}`))
	require.ErrorIs(t, err, ErrWebAgentInvalid)
}
func TestWebAgentOfficeClientDoesNotForwardSecretsOnRedirect(t *testing.T) {
	hit := false
	target := httptest.NewServer(http.HandlerFunc(func(http.ResponseWriter, *http.Request) { hit = true }))
	defer target.Close()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, target.URL, http.StatusTemporaryRedirect)
	}))
	defer server.Close()
	client, err := NewWebAgentOfficeClient(server.URL, strings.Repeat("s", 32))
	require.NoError(t, err)
	_, err = client.Render(context.Background(), "document", json.RawMessage(`{"kind":"document"}`))
	require.Error(t, err)
	require.False(t, hit)
}
func TestWebAgentOfficeArchiveRejectsActiveAndTraversalContent(t *testing.T) {
	for _, parts := range []map[string]string{
		{"../secret": "data"},
		{"word/vbaProject.bin": "macro"},
		{"word/_rels/document.xml.rels": `<Relationships><Relationship TargetMode="External" Target="https://example.com"/></Relationships>`},
		{"word/_rels/document.xml.rels": `<Relationships><Relationship Target="https://example.com"/></Relationships>`},
		{"word/embeddings/unsafe.xlsx": "not a workbook"},
	} {
		require.Error(t, validateWebAgentOfficeArchive(officeArchive(t, parts), "word/document.xml"))
	}
}
func TestWebAgentArtifactStoreIsPrivateAndBounded(t *testing.T) {
	root := filepath.Join(t.TempDir(), "private-artifacts")
	store, err := NewWebAgentFileStore(root)
	require.NoError(t, err)
	key, err := store.Put(context.Background(), "docx", []byte("test"))
	require.NoError(t, err)
	info, err := os.Stat(filepath.Join(root, key))
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0600), info.Mode().Perm())
	reader, size, err := store.Open(context.Background(), key)
	require.NoError(t, err)
	require.Equal(t, int64(4), size)
	data, err := io.ReadAll(reader)
	reader.Close()
	require.NoError(t, err)
	require.Equal(t, "test", string(data))
	_, _, err = store.Open(context.Background(), "../etc/passwd")
	require.ErrorIs(t, err, ErrWebAgentInvalid)
	_, err = store.Put(context.Background(), "../txt", []byte("bad"))
	require.ErrorIs(t, err, ErrWebAgentInvalid)
	require.NoError(t, store.Remove(context.Background(), key))
	require.NoError(t, store.Remove(context.Background(), key))
	require.NoError(t, os.Chmod(root, 0755))
	_, err = NewWebAgentFileStore(root)
	require.ErrorIs(t, err, ErrWebAgentInvalid)
}

// Use only synthetic artifacts generated by the isolated renderer test image.
func TestWebAgentOfficeRealRenderedArchives(t *testing.T) {
	root := os.Getenv("WEB_AGENT_OFFICE_TEST_OUTPUT")
	if root == "" {
		t.Skip("set WEB_AGENT_OFFICE_TEST_OUTPUT to renderer test samples")
	}
	for kind, format := range webAgentArtifactTypes {
		t.Run(kind, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join(root, "sample."+format.ext))
			require.NoError(t, err)
			require.NoError(t, validateWebAgentOfficeArchive(data, format.entry))
		})
	}
}

func TestWebAgentArtifactRejectsOverflowedSize(t *testing.T) {
	a := &WebAgentArtifact{Kind: "document", Title: "test", Filename: "test.docx", MIME: webAgentArtifactTypes["document"].mime,
		BlobKey: "ffffffff-ffff-ffff-ffff-ffffffffffff.docx", PreviewKey: "ffffffff-ffff-ffff-ffff-ffffffffffff.pdf",
		SizeBytes: math.MaxInt64, PreviewBytes: math.MaxInt64, SHA256: strings.Repeat("a", 64), Spec: json.RawMessage(`{"kind":"document","title":"test"}`)}
	require.ErrorIs(t, a.Validate(), ErrWebAgentInvalid)
}
