<template>
  <div class="rounded-xl border border-gray-200 p-4 dark:border-dark-700">
    <div class="flex items-center justify-between"><div><h3 class="text-sm font-semibold">{{ t('admin.settings.features.webChat.systemTemplates') }}</h3><p class="text-xs text-gray-500">{{ t('admin.settings.features.webChat.systemTemplatesHint') }}</p></div><button class="btn btn-secondary btn-sm" @click="open(null)">+ {{ t('common.add') }}</button></div>
    <div class="mt-3 space-y-2"><div v-for="item in templates" :key="item.id" class="flex items-center gap-3 rounded-lg bg-gray-50 p-3 dark:bg-dark-800"><div class="min-w-0 flex-1"><div class="flex gap-2"><strong class="truncate text-sm">{{ item.name }}</strong><span class="text-xs" :class="item.enabled?'text-green-600':'text-gray-400'">{{ item.enabled?t('common.enabled'):t('common.disabled') }}</span></div><p class="truncate text-xs text-gray-500">{{ item.category }} · {{ item.language }}</p></div><button class="btn btn-secondary btn-sm" @click="open(item)">{{ t('common.edit') }}</button></div><p v-if="!templates.length" class="py-4 text-center text-xs text-gray-500">{{ t('common.noData') }}</p></div>
    <BaseDialog :show="dialog" :title="current?t('common.edit'):t('common.add')" width="wide" @close="dialog=false"><div class="space-y-3"><div class="grid grid-cols-2 gap-3"><label class="field">{{ t('common.name') }}<input v-model="form.name" class="input"/></label><label class="field">{{ t('webChat.category') }}<input v-model="form.category" class="input"/></label></div><label class="field">{{ t('common.description') }}<input v-model="form.description" class="input"/></label><label class="field">{{ t('webChat.templateBody') }}<textarea v-model="form.body" class="input font-mono" rows="8"/></label><div v-for="(v,i) in form.variables" :key="i" class="grid grid-cols-[1fr_1fr_8rem_auto] gap-2"><input v-model="v.name" class="input" placeholder="variable_name"/><input v-model="v.label" class="input" :placeholder="t('webChat.variableLabel')"/><select v-model="v.type" class="input"><option value="singleline">{{ t('webChat.singleLine') }}</option><option value="multiline">{{ t('webChat.multiLine') }}</option></select><button @click="form.variables.splice(i,1)">×</button></div><button class="btn btn-secondary btn-sm" @click="form.variables.push({name:'',label:'',required:false,default_value:'',type:'singleline'})">+ {{ t('webChat.addVariable') }}</button><div class="grid grid-cols-3 gap-3"><label class="field">{{ t('webChat.language') }}<select v-model="form.language" class="input"><option value="zh-CN">中文</option><option value="en">English</option></select></label><label class="field">{{ t('webChat.sortOrder') }}<input v-model.number="form.sort_order" type="number" class="input"/></label><label class="mt-6"><input v-model="form.enabled" type="checkbox"/> {{ t('common.enabled') }}</label></div><p v-if="error" class="text-sm text-red-500">{{ error }}</p></div><template #footer><div class="flex justify-between"><button v-if="current" class="btn btn-secondary text-red-600" @click="remove">{{ t('common.delete') }}</button><span v-else/><div class="flex gap-2"><button class="btn btn-secondary" @click="dialog=false">{{ t('common.cancel') }}</button><button class="btn btn-primary" :disabled="saving" @click="save">{{ t('common.save') }}</button></div></div></template></BaseDialog>
  </div>
</template>
<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{useI18n}from'vue-i18n';import BaseDialog from '@/components/common/BaseDialog.vue';import webChatAPI,{type WebChatTemplate,type WebChatTemplateInput}from'@/api/webChat';import{extractApiErrorMessage}from'@/utils/apiError';const{t}=useI18n();const templates=ref<WebChatTemplate[]>([]),dialog=ref(false),current=ref<WebChatTemplate|null>(null),saving=ref(false),error=ref('');const form=reactive<WebChatTemplateInput>({name:'',category:'',description:'',body:'',variables:[],language:'zh-CN',enabled:true,sort_order:0});onMounted(load);async function load(){templates.value=await webChatAPI.adminListTemplates()}function open(item:WebChatTemplate|null){current.value=item;Object.assign(form,item?{name:item.name,category:item.category,description:item.description,body:item.body,variables:item.variables.map(v=>({...v})),language:item.language,enabled:item.enabled,sort_order:item.sort_order}:{name:'',category:'',description:'',body:'',variables:[],language:'zh-CN',enabled:true,sort_order:0});error.value='';dialog.value=true}async function save(){saving.value=true;try{current.value?await webChatAPI.adminPatchTemplate(current.value.id,{...form,variables:form.variables.map(v=>({...v}))}):await webChatAPI.adminCreateTemplate({...form,variables:form.variables.map(v=>({...v}))});dialog.value=false;await load()}catch(e){error.value=extractApiErrorMessage(e)}finally{saving.value=false}}async function remove(){if(!current.value||!confirm(t('webChat.deleteTemplateConfirm')))return;await webChatAPI.adminDeleteTemplate(current.value.id);dialog.value=false;await load()}
</script><style scoped>.field{display:flex;flex-direction:column;gap:.3rem;font-size:.75rem;font-weight:700;color:#64748b}</style>
