<template>
  <BaseDialog :show="show" :title="t('webChat.templateLibrary')" width="wide" @close="emit('close')">
    <div class="template-shell">
      <aside class="template-list">
        <div class="flex gap-2"><button class="tab" :class="{active:scope==='all'}" @click="scope='all'">{{ t('common.all') }}</button><button class="tab" :class="{active:scope==='personal'}" @click="scope='personal'">{{ t('webChat.personalTemplates') }}</button></div>
        <button v-for="item in visibleTemplates" :key="item.id" class="template-item" :class="{active:item.id===selected?.id}" @click="select(item)"><strong>{{ item.name }}</strong><span>{{ item.category }} · {{ item.scope==='system'?t('webChat.systemTemplate'):t('webChat.personalTemplate') }}</span></button>
        <button class="new-personal" @click="startCreate">+ {{ t('webChat.newPersonalTemplate') }}</button>
      </aside>
      <section v-if="editing" class="template-main">
        <label class="field"><span>{{ t('common.name') }}</span><input v-model="editor.name" class="input" maxlength="120" /></label>
        <div class="grid grid-cols-2 gap-3"><label class="field"><span>{{ t('webChat.category') }}</span><input v-model="editor.category" class="input" /></label><label class="field"><span>{{ t('webChat.language') }}</span><select v-model="editor.language" class="input"><option value="zh-CN">中文</option><option value="en">English</option></select></label></div>
        <label class="field"><span>{{ t('common.description') }}</span><input v-model="editor.description" class="input" maxlength="500" /></label>
        <label class="field"><span>{{ t('webChat.templateBody') }}</span><textarea v-model="editor.body" class="input font-mono" rows="8" maxlength="20000" /></label>
        <p class="text-xs text-gray-500">{{ t('webChat.templateVariableHint') }}</p>
        <div v-for="(v,index) in editor.variables" :key="index" class="variable-row"><input v-model="v.name" class="input" placeholder="variable_name"/><input v-model="v.label" class="input" :placeholder="t('webChat.variableLabel')"/><select v-model="v.type" class="input"><option value="singleline">{{ t('webChat.singleLine') }}</option><option value="multiline">{{ t('webChat.multiLine') }}</option></select><label><input v-model="v.required" type="checkbox"/> {{ t('webChat.required') }}</label><button @click="editor.variables.splice(index,1)">×</button></div>
        <button v-if="editor.variables.length<20" class="btn btn-secondary btn-sm" @click="editor.variables.push(blankVariable())">+ {{ t('webChat.addVariable') }}</button>
        <div class="mt-4 flex justify-between"><button v-if="selected?.scope==='personal'" class="btn btn-secondary text-red-600" @click="removePersonal">{{ t('common.delete') }}</button><span v-else/><div class="flex gap-2"><button class="btn btn-secondary" @click="editing=false">{{ t('common.cancel') }}</button><button class="btn btn-primary" :disabled="saving" @click="savePersonal">{{ t('common.save') }}</button></div></div>
      </section>
      <section v-else-if="selected" class="template-main">
        <div><p class="text-xs font-bold uppercase tracking-wider text-primary-600">{{ selected.category }}</p><h3 class="mt-1 text-xl font-black">{{ selected.name }}</h3><p class="mt-1 text-sm text-gray-500">{{ selected.description }}</p></div>
        <div v-for="variable in selected.variables" :key="variable.name" class="field"><span>{{ variable.label }} <b v-if="variable.required" class="text-red-500">*</b></span><textarea v-if="variable.type==='multiline'" v-model="values[variable.name]" rows="4" class="input"/><input v-else v-model="values[variable.name]" class="input"/></div>
        <div><p class="field-label">{{ t('webChat.preview') }}</p><pre class="preview">{{ rendered }}</pre></div>
        <p v-if="error" class="text-sm text-red-500">{{ error }}</p>
        <div class="flex justify-between"><div class="flex gap-2"><button v-if="selected.scope==='system'" class="btn btn-secondary" @click="copyPersonal">{{ t('webChat.copyAsPersonal') }}</button><button v-else class="btn btn-secondary" @click="startEdit">{{ t('common.edit') }}</button></div><button class="btn btn-primary" :disabled="!valid" @click="emit('apply',rendered,selected.id)">{{ t('webChat.insertTemplate') }}</button></div>
      </section>
      <div v-else class="template-main items-center justify-center text-gray-500">{{ t('webChat.chooseTemplate') }}</div>
    </div>
  </BaseDialog>
</template>
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';import { useI18n } from 'vue-i18n';import BaseDialog from '@/components/common/BaseDialog.vue';import webChatAPI,{type WebChatTemplate,type WebChatTemplateInput,type WebChatTemplateVariable}from '@/api/webChat';import{extractApiErrorMessage}from '@/utils/apiError';import{missingRequiredTemplateVariables,renderWebChatTemplate}from '@/utils/webChatTemplates'
const props=defineProps<{show:boolean;templates:WebChatTemplate[]}>();const emit=defineEmits<{close:[];apply:[string,number];changed:[]}>();const{t}=useI18n();const selected=ref<WebChatTemplate|null>(null),scope=ref<'all'|'personal'>('all'),values=reactive<Record<string,string>>({}),editing=ref(false),saving=ref(false),error=ref('')
const editor=reactive<WebChatTemplateInput>({name:'',category:'',description:'',body:'',variables:[],language:'zh-CN',enabled:true,sort_order:0});const visibleTemplates=computed(()=>props.templates.filter(x=>scope.value==='all'||x.scope==='personal'));const rendered=computed(()=>selected.value?renderWebChatTemplate(selected.value,values):'');const valid=computed(()=>Boolean(selected.value&&missingRequiredTemplateVariables(selected.value.variables,values).length===0))
watch(()=>[props.show,props.templates] as const,()=>{if(props.show&&!selected.value&&props.templates[0])select(props.templates[0])},{immediate:true});function select(item:WebChatTemplate){selected.value=item;editing.value=false;error.value='';for(const k of Object.keys(values))delete values[k];for(const v of item.variables)values[v.name]=v.default_value||''}function blankVariable():WebChatTemplateVariable{return{name:'',label:'',required:false,default_value:'',type:'singleline'}}
function startCreate(){selected.value=null;editing.value=true;Object.assign(editor,{name:'',category:'',description:'',body:'',variables:[],language:'zh-CN',enabled:true,sort_order:0})}function startEdit(){if(!selected.value)return;editing.value=true;Object.assign(editor,{name:selected.value.name,category:selected.value.category,description:selected.value.description,body:selected.value.body,variables:selected.value.variables.map(v=>({...v})),language:selected.value.language,enabled:selected.value.enabled,sort_order:selected.value.sort_order})}
async function savePersonal(){saving.value=true;error.value='';try{const item=selected.value?.scope==='personal'?await webChatAPI.patchTemplate(selected.value.id,{...editor,variables:editor.variables.map(v=>({...v}))}):await webChatAPI.createTemplate({...editor,variables:editor.variables.map(v=>({...v}))});emit('changed');select(item)}catch(e){error.value=extractApiErrorMessage(e)}finally{saving.value=false}}async function copyPersonal(){if(!selected.value)return;try{const item=await webChatAPI.copyTemplate(selected.value.id);emit('changed');select(item)}catch(e){error.value=extractApiErrorMessage(e)}}async function removePersonal(){if(!selected.value||!confirm(t('webChat.deleteTemplateConfirm')))return;await webChatAPI.deleteTemplate(selected.value.id);selected.value=null;editing.value=false;emit('changed')}
</script>
<style scoped>.template-shell{display:grid;grid-template-columns:15rem minmax(0,1fr);min-height:32rem;gap:1rem}.template-list{display:flex;flex-direction:column;gap:.4rem;border-right:1px solid rgba(148,163,184,.25);padding-right:1rem}.tab{border-radius:.6rem;padding:.35rem .55rem;font-size:.72rem}.tab.active{background:rgba(20,184,166,.12);color:#0f766e}.template-item{display:flex;flex-direction:column;border:1px solid transparent;border-radius:.8rem;padding:.65rem;text-align:left}.template-item span{font-size:.68rem;color:#64748b}.template-item.active,.template-item:hover{border-color:rgba(20,184,166,.3);background:rgba(20,184,166,.07)}.new-personal{margin-top:auto;border:1px dashed #94a3b8;border-radius:.8rem;padding:.6rem;font-size:.75rem}.template-main{display:flex;min-width:0;flex-direction:column;gap:1rem}.field{display:flex;flex-direction:column;gap:.3rem;font-size:.75rem;font-weight:700;color:#64748b}.field-label{font-size:.72rem;font-weight:800;color:#64748b}.preview{max-height:14rem;overflow:auto;white-space:pre-wrap;border-radius:.8rem;background:rgba(148,163,184,.1);padding:.8rem;font-size:.8rem}.variable-row{display:grid;grid-template-columns:1fr 1fr 8rem auto auto;align-items:center;gap:.4rem;font-size:.72rem}@media(max-width:767px){.template-shell{display:block}.template-list{max-height:12rem;overflow:auto;border-right:0;border-bottom:1px solid rgba(148,163,184,.25);padding:0 0 .75rem;margin-bottom:1rem}.variable-row{grid-template-columns:1fr 1fr}}</style>
